// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="StreamingMaxPool_hls_5_StreamingMaxPool_hls_5,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.333000,HLS_SYN_LAT=3301,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=77,HLS_SYN_LUT=493,HLS_VERSION=2024_1}" *)

module StreamingMaxPool_hls_5 (
        ap_clk,
        ap_rst_n,
        in0_V_TDATA,
        in0_V_TVALID,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        out_V_TREADY
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst_n;
input  [7:0] in0_V_TDATA;
input   in0_V_TVALID;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;
input   out_V_TREADY;

 reg    ap_rst_n_inv;
reg   [5:0] buf_address0;
reg    buf_ce0;
reg    buf_we0;
reg   [1:0] buf_d0;
wire   [1:0] buf_q0;
reg    buf_ce1;
wire   [1:0] buf_q1;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_start;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_done;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_idle;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_ready;
wire   [5:0] grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_address0;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_ce0;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_we0;
wire   [1:0] grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_d0;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_start;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_done;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_idle;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_ready;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_in0_V_TREADY;
wire   [5:0] grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_address0;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_ce0;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_we0;
wire   [1:0] grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_d0;
wire   [5:0] grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_address1;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_ce1;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_start;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_done;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_idle;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_ready;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_out_V_TREADY;
wire   [5:0] grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_address0;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_ce0;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_we0;
wire   [1:0] grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_d0;
wire   [7:0] grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_out_V_TDATA;
wire    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_out_V_TVALID;
reg    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_start_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
reg    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln267_fu_86_p2;
wire    ap_CS_fsm_state4;
reg    grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [4:0] xp_fu_50;
wire   [4:0] xp_2_fu_92_p2;
reg   [7:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_both_out_V_U_apdone_blk;
wire    ap_CS_fsm_state8;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [7:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
wire    out_V_TREADY_int_regslice;
wire    regslice_both_out_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_start_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_start_reg = 1'b0;
#0 grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_start_reg = 1'b0;
#0 xp_fu_50 = 5'd0;
end

StreamingMaxPool_hls_5_buf_RAM_AUTO_1R1W #(
    .DataWidth( 2 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf_address0),
    .ce0(buf_ce0),
    .we0(buf_we0),
    .d0(buf_d0),
    .q0(buf_q0),
    .address1(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_address1),
    .ce1(buf_ce1),
    .q1(buf_q1)
);

StreamingMaxPool_hls_5_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1 grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_start),
    .ap_done(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_done),
    .ap_idle(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_idle),
    .ap_ready(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_ready),
    .buf_r_address0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_address0),
    .buf_r_ce0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_ce0),
    .buf_r_we0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_we0),
    .buf_r_d0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_d0)
);

StreamingMaxPool_hls_5_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5 grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_start),
    .ap_done(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_done),
    .ap_idle(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_idle),
    .ap_ready(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_ready),
    .in0_V_TVALID(in0_V_TVALID_int_regslice),
    .in0_V_TDATA(in0_V_TDATA_int_regslice),
    .in0_V_TREADY(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_in0_V_TREADY),
    .buf_r_address0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_address0),
    .buf_r_ce0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_ce0),
    .buf_r_we0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_we0),
    .buf_r_d0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_d0),
    .buf_r_address1(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_address1),
    .buf_r_ce1(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_ce1),
    .buf_r_q1(buf_q1)
);

StreamingMaxPool_hls_5_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7 grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_start),
    .ap_done(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_done),
    .ap_idle(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_idle),
    .ap_ready(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_ready),
    .out_V_TREADY(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_out_V_TREADY),
    .buf_r_address0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_address0),
    .buf_r_ce0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_ce0),
    .buf_r_we0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_we0),
    .buf_r_d0(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_d0),
    .buf_r_q0(buf_q0),
    .out_V_TDATA(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_out_V_TDATA),
    .out_V_TVALID(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_out_V_TVALID)
);

StreamingMaxPool_hls_5_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

StreamingMaxPool_hls_5_regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_out_V_TDATA),
    .vld_in(grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_out_V_TVALID),
    .ack_in(out_V_TREADY_int_regslice),
    .data_out(out_V_TDATA),
    .vld_out(regslice_both_out_V_U_vld_out),
    .ack_out(out_V_TREADY),
    .apdone_blk(regslice_both_out_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_ready == 1'b1)) begin
            grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln267_fu_86_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_ready == 1'b1)) begin
            grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_start_reg <= 1'b1;
        end else if ((grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_ready == 1'b1)) begin
            grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        xp_fu_50 <= 5'd0;
    end else if (((icmp_ln267_fu_86_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        xp_fu_50 <= xp_2_fu_92_p2;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_address0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_address0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_address0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_address0;
    end else begin
        buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_ce0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_ce0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_ce0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_ce0;
    end else begin
        buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_ce1 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_ce1;
    end else begin
        buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_d0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_d0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_d0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_d0;
    end else begin
        buf_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_we0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_buf_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_we0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_buf_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_we0 = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_buf_r_we0;
    end else begin
        buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        in0_V_TREADY_int_regslice = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_in0_V_TREADY;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln267_fu_86_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (regslice_both_out_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_start = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_257_1_fu_58_ap_start_reg;

assign grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_start = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_269_4_VITIS_LOOP_271_5_fu_64_ap_start_reg;

assign grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_start = grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_ap_start_reg;

assign grp_StreamingMaxPool_hls_5_Pipeline_VITIS_LOOP_287_7_fu_71_out_V_TREADY = (out_V_TREADY_int_regslice & ap_CS_fsm_state7);

assign icmp_ln267_fu_86_p2 = ((xp_fu_50 == 5'd16) ? 1'b1 : 1'b0);

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign out_V_TVALID = regslice_both_out_V_U_vld_out;

assign xp_2_fu_92_p2 = (xp_fu_50 + 5'd1);

endmodule //StreamingMaxPool_hls_5
