// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [47:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [15:0] out_V_TDATA;
output   out_V_TVALID;
input  [15:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
reg   [1:0] ap_CS_iter5_fsm;
wire    ap_CS_iter5_fsm_state0;
wire   [0:0] icmp_ln249_fu_133_p2;
wire   [0:0] icmp_ln253_fu_145_p2;
reg    ap_predicate_op28_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] icmp_ln249_reg_418;
reg   [0:0] icmp_ln249_reg_418_pp0_iter4_reg;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_state6_io;
wire    ap_CS_iter5_fsm_state6;
reg    ap_block_state5_pp0_stage0_iter4;
wire    ap_CS_iter4_fsm_state5;
reg    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [0:0] icmp_ln249_reg_418_pp0_iter1_reg;
reg   [0:0] icmp_ln249_reg_418_pp0_iter2_reg;
reg   [0:0] icmp_ln249_reg_418_pp0_iter3_reg;
wire   [1:0] local_temp_fu_156_p1;
reg   [1:0] local_temp_reg_425;
reg   [1:0] local_temp_reg_425_pp0_iter1_reg;
reg  signed [1:0] local_temp_reg_425_pp0_iter2_reg;
reg   [1:0] local_temp_1_reg_430;
reg  signed [1:0] local_temp_1_reg_430_pp0_iter1_reg;
reg  signed [1:0] local_temp_2_reg_435;
reg   [1:0] local_temp_3_reg_440;
reg  signed [1:0] local_temp_3_reg_440_pp0_iter1_reg;
reg   [1:0] local_temp_4_reg_445;
reg   [1:0] local_temp_4_reg_445_pp0_iter1_reg;
reg  signed [1:0] local_temp_4_reg_445_pp0_iter2_reg;
reg  signed [1:0] local_temp_5_reg_450;
wire   [7:0] r_fu_243_p1;
reg   [7:0] r_reg_455;
reg  signed [7:0] r_reg_455_pp0_iter2_reg;
reg  signed [7:0] r_1_reg_460;
reg  signed [7:0] r_3_reg_475;
reg   [7:0] r_4_reg_480;
reg  signed [7:0] r_4_reg_480_pp0_iter2_reg;
wire  signed [10:0] grp_fu_364_p3;
wire  signed [10:0] grp_fu_372_p3;
reg   [31:0] nf_fu_86;
wire   [31:0] nf_5_fu_222_p3;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_nf_3;
reg   [16:0] i_fu_90;
wire   [16:0] i_2_fu_139_p2;
reg   [16:0] ap_sig_allocacmp_i_1;
reg   [47:0] arrayidx3_0_0_0_load16_fu_94;
wire   [31:0] nf_4_fu_210_p2;
wire   [0:0] icmp_ln302_fu_216_p2;
wire  signed [7:0] r_2_fu_257_p4;
wire  signed [7:0] r_5_fu_294_p4;
wire  signed [9:0] mul_ln90_fu_329_p2;
wire  signed [9:0] mul_ln90_4_fu_345_p2;
wire  signed [10:0] grp_fu_389_p3;
wire  signed [10:0] grp_fu_380_p3;
(* use_dsp48 = "no" *) wire   [10:0] outElem_fu_355_p2;
reg    grp_fu_364_ce;
reg    grp_fu_372_ce;
reg    grp_fu_380_ce;
reg    grp_fu_389_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
reg    ap_ST_iter4_fsm_state5_blk;
reg    ap_ST_iter5_fsm_state6_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_144;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
#0 nf_fu_86 = 32'd0;
#0 i_fu_90 = 17'd0;
#0 arrayidx3_0_0_0_load16_fu_94 = 48'd0;
#0 ap_done_reg = 1'b0;
end

MVAU_hls_0_mul_8s_2s_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mul_8s_2s_10_1_1_U1(
    .din0(r_reg_455_pp0_iter2_reg),
    .din1(local_temp_reg_425_pp0_iter2_reg),
    .dout(mul_ln90_fu_329_p2)
);

MVAU_hls_0_mul_8s_2s_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mul_8s_2s_10_1_1_U2(
    .din0(r_4_reg_480_pp0_iter2_reg),
    .din1(local_temp_4_reg_445_pp0_iter2_reg),
    .dout(mul_ln90_4_fu_345_p2)
);

MVAU_hls_0_mac_muladd_8s_2s_10s_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
mac_muladd_8s_2s_10s_11_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_2_fu_257_p4),
    .din1(local_temp_2_reg_435),
    .din2(mul_ln90_fu_329_p2),
    .ce(grp_fu_364_ce),
    .dout(grp_fu_364_p3)
);

MVAU_hls_0_mac_muladd_8s_2s_10s_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
mac_muladd_8s_2s_10s_11_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_5_fu_294_p4),
    .din1(local_temp_5_reg_450),
    .din2(mul_ln90_4_fu_345_p2),
    .ce(grp_fu_372_ce),
    .dout(grp_fu_372_p3)
);

MVAU_hls_0_mac_muladd_8s_2s_11s_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
mac_muladd_8s_2s_11s_11_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_1_reg_460),
    .din1(local_temp_1_reg_430_pp0_iter1_reg),
    .din2(grp_fu_364_p3),
    .ce(grp_fu_380_ce),
    .dout(grp_fu_380_p3)
);

MVAU_hls_0_mac_muladd_8s_2s_11s_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
mac_muladd_8s_2s_11s_11_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_3_reg_475),
    .din1(local_temp_3_reg_440_pp0_iter1_reg),
    .din2(grp_fu_372_p3),
    .ce(grp_fu_389_ce),
    .dout(grp_fu_389_p3)
);

MVAU_hls_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)) & (1'b1 == ap_CS_iter5_fsm_state6) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)) & (1'b1 == ap_CS_iter5_fsm_state6) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if ((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((icmp_ln249_fu_133_p2 == 1'd0)) begin
            i_fu_90 <= i_2_fu_139_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_90 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((icmp_ln249_fu_133_p2 == 1'd0)) begin
            nf_fu_86 <= nf_5_fu_222_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_fu_86 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_418 <= icmp_ln249_fu_133_p2;
        local_temp_1_reg_430 <= {{weights_V_TDATA[3:2]}};
        local_temp_2_reg_435 <= {{weights_V_TDATA[5:4]}};
        local_temp_3_reg_440 <= {{weights_V_TDATA[7:6]}};
        local_temp_4_reg_445 <= {{weights_V_TDATA[9:8]}};
        local_temp_5_reg_450 <= {{weights_V_TDATA[11:10]}};
        local_temp_reg_425 <= local_temp_fu_156_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln249_reg_418_pp0_iter1_reg <= icmp_ln249_reg_418;
        local_temp_1_reg_430_pp0_iter1_reg <= local_temp_1_reg_430;
        local_temp_3_reg_440_pp0_iter1_reg <= local_temp_3_reg_440;
        local_temp_4_reg_445_pp0_iter1_reg <= local_temp_4_reg_445;
        local_temp_reg_425_pp0_iter1_reg <= local_temp_reg_425;
        r_1_reg_460 <= {{arrayidx3_0_0_0_load16_fu_94[15:8]}};
        r_3_reg_475 <= {{arrayidx3_0_0_0_load16_fu_94[31:24]}};
        r_4_reg_480 <= {{arrayidx3_0_0_0_load16_fu_94[39:32]}};
        r_reg_455 <= r_fu_243_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln249_reg_418_pp0_iter2_reg <= icmp_ln249_reg_418_pp0_iter1_reg;
        local_temp_4_reg_445_pp0_iter2_reg <= local_temp_4_reg_445_pp0_iter1_reg;
        local_temp_reg_425_pp0_iter2_reg <= local_temp_reg_425_pp0_iter1_reg;
        r_4_reg_480_pp0_iter2_reg <= r_4_reg_480;
        r_reg_455_pp0_iter2_reg <= r_reg_455;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln249_reg_418_pp0_iter3_reg <= icmp_ln249_reg_418_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (icmp_ln253_fu_145_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_133_p2 == 1'd0))) begin
        arrayidx3_0_0_0_load16_fu_94 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        icmp_ln249_reg_418_pp0_iter4_reg <= icmp_ln249_reg_418_pp0_iter3_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_pp0_stage0_iter2)) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4_pp0_stage0_iter3)) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5_pp0_stage0_iter4)) begin
        ap_ST_iter4_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_iter4_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io))) begin
        ap_ST_iter5_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_iter5_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_133_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)) & (1'b1 == ap_CS_iter5_fsm_state6) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter5_fsm_state0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 17'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_90;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_3 = nf_fu_86;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) 
    & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_364_ce = 1'b1;
    end else begin
        grp_fu_364_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) 
    & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_372_ce = 1'b1;
    end else begin
        grp_fu_372_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)) & (1'b1 == ap_CS_iter5_fsm_state6)) | (~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
        grp_fu_380_ce = 1'b1;
    end else begin
        grp_fu_380_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)) & (1'b1 == ap_CS_iter5_fsm_state6)) | (~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
        grp_fu_389_ce = 1'b1;
    end else begin
        grp_fu_389_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op28_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (ap_predicate_op28_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln249_reg_418_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)) & (icmp_ln249_reg_418_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_133_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_133_p2 == 1'd0))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b0 == ap_block_state1_pp0_stage0_iter0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter2_fsm_state3) & (1'b0 == ap_block_state3_pp0_stage0_iter2))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & ((1'b0 == ap_CS_iter2_fsm_state3) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter3_fsm_state4) & (1'b0 == ap_block_state4_pp0_stage0_iter3))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & ((1'b0 == ap_CS_iter3_fsm_state4) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3))))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if ((~((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)) & ((1'b0 == ap_CS_iter4_fsm_state5) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4))))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else if (((~((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)) & (icmp_ln249_reg_418_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_iter5_fsm_state6)) | (~((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)) & (1'b1 == ap_CS_iter4_fsm_state5) & (1'b0 == ap_block_state5_pp0_stage0_iter4)))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state0 = ap_CS_iter5_fsm[32'd0];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_133_p2 == 1'd0)) | ((ap_predicate_op28_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_state6_io = ((icmp_ln249_reg_418_pp0_iter4_reg == 1'd0) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((icmp_ln249_reg_418_pp0_iter4_reg == 1'd0) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_144 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_pp0_stage0_iter5) | (1'b1 == ap_block_state6_io)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op28_read_state1 = ((icmp_ln253_fu_145_p2 == 1'd1) & (icmp_ln249_fu_133_p2 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign i_2_fu_139_p2 = (ap_sig_allocacmp_i_1 + 17'd1);

assign icmp_ln249_fu_133_p2 = ((ap_sig_allocacmp_i_1 == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_145_p2 = ((ap_sig_allocacmp_nf_3 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_216_p2 = ((nf_4_fu_210_p2 == 32'd64) ? 1'b1 : 1'b0);

assign local_temp_fu_156_p1 = weights_V_TDATA[1:0];

assign nf_4_fu_210_p2 = (ap_sig_allocacmp_nf_3 + 32'd1);

assign nf_5_fu_222_p3 = ((icmp_ln302_fu_216_p2[0:0] == 1'b1) ? 32'd0 : nf_4_fu_210_p2);

assign outElem_fu_355_p2 = ($signed(grp_fu_389_p3) + $signed(grp_fu_380_p3));

assign out_V_TDATA = outElem_fu_355_p2;

assign r_2_fu_257_p4 = {{arrayidx3_0_0_0_load16_fu_94[23:16]}};

assign r_5_fu_294_p4 = {{arrayidx3_0_0_0_load16_fu_94[47:40]}};

assign r_fu_243_p1 = arrayidx3_0_0_0_load16_fu_94[7:0];

endmodule //MVAU_hls_0_Matrix_Vector_Activate_Stream_Batch
