// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MVAU_hls_3_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter6_fsm_state7 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;
parameter    ap_ST_iter6_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [47:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [15:0] out_V_TDATA;
output   out_V_TVALID;
input  [47:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
reg   [1:0] ap_CS_iter5_fsm;
wire    ap_CS_iter5_fsm_state0;
reg   [1:0] ap_CS_iter6_fsm;
wire    ap_CS_iter6_fsm_state0;
wire   [0:0] icmp_ln249_fu_272_p2;
wire   [0:0] icmp_ln253_fu_288_p2;
reg    ap_predicate_op51_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
wire    ap_CS_iter5_fsm_state6;
wire    ap_CS_iter4_fsm_state5;
wire    ap_CS_iter3_fsm_state4;
wire    ap_CS_iter2_fsm_state3;
reg   [0:0] icmp_ln249_reg_1514;
reg   [0:0] icmp_ln249_reg_1514_pp0_iter5_reg;
reg   [0:0] icmp_ln290_reg_1668;
reg   [0:0] icmp_ln290_reg_1668_pp0_iter5_reg;
reg    ap_predicate_op321_write_state7;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_state7_io;
wire    ap_CS_iter6_fsm_state7;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [0:0] icmp_ln249_reg_1514_pp0_iter1_reg;
reg   [0:0] icmp_ln249_reg_1514_pp0_iter2_reg;
reg   [0:0] icmp_ln249_reg_1514_pp0_iter3_reg;
reg   [0:0] icmp_ln249_reg_1514_pp0_iter4_reg;
wire   [2:0] trunc_ln249_fu_284_p1;
wire   [47:0] tmp_fu_318_p19;
wire   [0:0] icmp_ln272_fu_398_p2;
reg   [0:0] icmp_ln272_reg_1543;
reg   [0:0] icmp_ln272_reg_1543_pp0_iter1_reg;
reg   [0:0] icmp_ln272_reg_1543_pp0_iter2_reg;
reg   [0:0] icmp_ln272_reg_1543_pp0_iter3_reg;
reg   [0:0] icmp_ln272_reg_1543_pp0_iter4_reg;
wire   [1:0] local_temp_fu_404_p1;
reg  signed [1:0] local_temp_reg_1548;
reg   [1:0] local_temp_1_reg_1553;
reg   [1:0] local_temp_1_reg_1553_pp0_iter1_reg;
reg  signed [1:0] local_temp_1_reg_1553_pp0_iter2_reg;
reg   [1:0] local_temp_2_reg_1558;
reg  signed [1:0] local_temp_2_reg_1558_pp0_iter1_reg;
reg  signed [1:0] local_temp_3_reg_1563;
reg   [1:0] local_temp_4_reg_1568;
reg   [1:0] local_temp_4_reg_1568_pp0_iter1_reg;
reg  signed [1:0] local_temp_4_reg_1568_pp0_iter2_reg;
reg   [1:0] local_temp_5_reg_1573;
reg  signed [1:0] local_temp_5_reg_1573_pp0_iter1_reg;
reg  signed [1:0] local_temp_6_reg_1578;
reg   [1:0] local_temp_7_reg_1583;
reg   [1:0] local_temp_7_reg_1583_pp0_iter1_reg;
reg  signed [1:0] local_temp_7_reg_1583_pp0_iter2_reg;
reg   [1:0] local_temp_8_reg_1588;
reg   [1:0] local_temp_8_reg_1588_pp0_iter1_reg;
reg  signed [1:0] local_temp_8_reg_1588_pp0_iter2_reg;
reg   [1:0] local_temp_9_reg_1593;
reg   [1:0] local_temp_9_reg_1593_pp0_iter1_reg;
reg  signed [1:0] local_temp_9_reg_1593_pp0_iter2_reg;
reg  signed [1:0] local_temp_10_reg_1598;
reg   [1:0] local_temp_11_reg_1603;
reg   [1:0] local_temp_11_reg_1603_pp0_iter1_reg;
reg  signed [1:0] local_temp_11_reg_1603_pp0_iter2_reg;
reg   [1:0] local_temp_12_reg_1608;
reg  signed [1:0] local_temp_12_reg_1608_pp0_iter1_reg;
reg  signed [1:0] local_temp_13_reg_1613;
reg   [1:0] local_temp_14_reg_1618;
reg   [1:0] local_temp_14_reg_1618_pp0_iter1_reg;
reg  signed [1:0] local_temp_14_reg_1618_pp0_iter2_reg;
reg   [1:0] local_temp_15_reg_1623;
reg  signed [1:0] local_temp_15_reg_1623_pp0_iter1_reg;
reg  signed [1:0] local_temp_16_reg_1628;
reg   [1:0] local_temp_17_reg_1633;
reg   [1:0] local_temp_17_reg_1633_pp0_iter1_reg;
reg  signed [1:0] local_temp_17_reg_1633_pp0_iter2_reg;
reg   [1:0] local_temp_18_reg_1638;
reg  signed [1:0] local_temp_18_reg_1638_pp0_iter1_reg;
reg  signed [1:0] local_temp_19_reg_1643;
reg   [1:0] local_temp_20_reg_1648;
reg  signed [1:0] local_temp_20_reg_1648_pp0_iter1_reg;
reg   [1:0] local_temp_21_reg_1653;
reg   [1:0] local_temp_21_reg_1653_pp0_iter1_reg;
reg  signed [1:0] local_temp_21_reg_1653_pp0_iter2_reg;
reg  signed [1:0] local_temp_22_reg_1658;
reg  signed [1:0] local_temp_23_reg_1663;
wire   [0:0] icmp_ln290_fu_644_p2;
reg   [0:0] icmp_ln290_reg_1668_pp0_iter1_reg;
reg   [0:0] icmp_ln290_reg_1668_pp0_iter2_reg;
reg   [0:0] icmp_ln290_reg_1668_pp0_iter3_reg;
reg   [0:0] icmp_ln290_reg_1668_pp0_iter4_reg;
reg   [1:0] r_1_reg_1682;
reg   [1:0] r_1_reg_1682_pp0_iter2_reg;
reg   [1:0] r_2_reg_1687;
reg   [1:0] r_4_reg_1702;
reg   [1:0] r_4_reg_1702_pp0_iter2_reg;
reg   [1:0] r_5_reg_1707;
reg   [1:0] r_7_reg_1722;
reg   [1:0] r_7_reg_1722_pp0_iter2_reg;
reg   [1:0] r_8_reg_1727;
reg   [1:0] r_8_reg_1727_pp0_iter2_reg;
reg   [1:0] r_9_reg_1732;
reg   [1:0] r_9_reg_1732_pp0_iter2_reg;
reg   [1:0] r_11_reg_1747;
reg   [1:0] r_11_reg_1747_pp0_iter2_reg;
reg   [1:0] r_12_reg_1752;
reg   [1:0] r_14_reg_1767;
reg   [1:0] r_14_reg_1767_pp0_iter2_reg;
reg   [1:0] r_15_reg_1772;
reg   [1:0] r_17_reg_1787;
reg   [1:0] r_17_reg_1787_pp0_iter2_reg;
reg   [1:0] r_18_reg_1792;
reg   [1:0] r_20_reg_1807;
reg   [1:0] r_21_reg_1812;
reg   [1:0] r_21_reg_1812_pp0_iter2_reg;
wire  signed [4:0] grp_fu_1367_p3;
reg  signed [4:0] add_ln169_reg_1942;
wire   [5:0] add_ln169_20_fu_1191_p2;
reg   [5:0] add_ln169_20_reg_1977;
wire   [8:0] outElem_fu_1289_p2;
reg   [8:0] outElem_reg_1982;
wire   [47:0] ap_phi_reg_pp0_iter0_inElem_reg_225;
reg   [47:0] ap_phi_reg_pp0_iter1_inElem_reg_225;
reg   [31:0] sf_fu_158;
wire   [31:0] sf_2_fu_638_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [16:0] i_fu_162;
wire   [16:0] i_2_fu_278_p2;
reg   [16:0] ap_sig_allocacmp_i_1;
reg   [8:0] empty_fu_166;
reg   [47:0] inputBuf_fu_170;
reg   [47:0] inputBuf_1_fu_174;
reg   [47:0] inputBuf_2_fu_178;
reg   [47:0] inputBuf_3_fu_182;
reg   [47:0] inputBuf_4_fu_186;
reg   [47:0] inputBuf_5_fu_190;
reg   [47:0] inputBuf_6_fu_194;
reg   [47:0] inputBuf_7_fu_198;
reg   [31:0] nf_fu_202;
wire   [31:0] nf_5_fu_667_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [47:0] tmp_fu_318_p17;
wire   [2:0] tmp_fu_318_p18;
wire   [31:0] nf_4_fu_655_p2;
wire   [0:0] icmp_ln302_fu_661_p2;
wire   [1:0] r_fu_690_p1;
wire   [1:0] r_3_fu_721_p4;
wire   [1:0] r_6_fu_758_p4;
wire   [1:0] r_10_fu_805_p4;
wire   [1:0] r_13_fu_842_p4;
wire   [1:0] r_16_fu_879_p4;
wire   [1:0] r_19_fu_916_p4;
wire   [1:0] r_22_fu_953_p4;
wire   [1:0] r_23_fu_970_p4;
wire   [1:0] mul_ln90_1_fu_1029_p0;
wire  signed [3:0] mul_ln90_1_fu_1029_p2;
wire   [1:0] mul_ln90_4_fu_1045_p0;
wire  signed [3:0] mul_ln90_4_fu_1045_p2;
wire   [1:0] mul_ln90_7_fu_1061_p0;
wire  signed [3:0] mul_ln90_7_fu_1061_p2;
wire   [1:0] mul_ln90_8_fu_1077_p0;
wire  signed [3:0] mul_ln90_8_fu_1077_p2;
wire   [1:0] mul_ln90_9_fu_1093_p0;
wire  signed [3:0] mul_ln90_9_fu_1093_p2;
wire   [1:0] mul_ln90_11_fu_1109_p0;
wire  signed [3:0] mul_ln90_11_fu_1109_p2;
wire   [1:0] mul_ln90_14_fu_1125_p0;
wire  signed [3:0] mul_ln90_14_fu_1125_p2;
wire   [1:0] mul_ln90_17_fu_1141_p0;
wire  signed [3:0] mul_ln90_17_fu_1141_p2;
wire   [1:0] mul_ln90_21_fu_1157_p0;
wire  signed [3:0] mul_ln90_21_fu_1157_p2;
wire  signed [4:0] grp_fu_1358_p3;
wire  signed [4:0] grp_fu_1340_p3;
wire  signed [4:0] grp_fu_1349_p3;
wire  signed [4:0] grp_fu_1304_p3;
wire  signed [4:0] grp_fu_1313_p3;
wire  signed [4:0] grp_fu_1322_p3;
wire  signed [4:0] grp_fu_1331_p3;
wire  signed [4:0] grp_fu_1375_p3;
wire  signed [5:0] sext_ln169_17_fu_1188_p1;
wire  signed [5:0] sext_ln169_16_fu_1185_p1;
wire  signed [8:0] sext_ln169_1_fu_1207_p1;
wire   [8:0] select_ln272_fu_1200_p3;
wire  signed [5:0] grp_fu_1429_p3;
wire  signed [8:0] sext_ln169_3_fu_1216_p1;
wire   [8:0] add_ln169_1_fu_1210_p2;
wire  signed [5:0] grp_fu_1420_p3;
wire  signed [5:0] grp_fu_1402_p3;
wire  signed [6:0] sext_ln169_7_fu_1228_p1;
wire  signed [6:0] sext_ln169_5_fu_1225_p1;
wire   [6:0] add_ln169_9_fu_1231_p2;
wire  signed [8:0] sext_ln169_8_fu_1237_p1;
wire   [8:0] add_ln169_4_fu_1219_p2;
wire  signed [5:0] grp_fu_1411_p3;
wire  signed [5:0] grp_fu_1384_p3;
wire  signed [6:0] sext_ln169_12_fu_1250_p1;
wire  signed [6:0] sext_ln169_10_fu_1247_p1;
wire   [6:0] add_ln169_15_fu_1253_p2;
wire  signed [5:0] grp_fu_1393_p3;
wire  signed [6:0] sext_ln169_18_fu_1266_p1;
wire  signed [6:0] sext_ln169_15_fu_1263_p1;
wire   [6:0] add_ln169_21_fu_1269_p2;
wire  signed [7:0] sext_ln169_19_fu_1275_p1;
wire  signed [7:0] sext_ln169_13_fu_1259_p1;
wire   [7:0] add_ln169_22_fu_1279_p2;
wire  signed [8:0] sext_ln169_20_fu_1285_p1;
wire   [8:0] add_ln169_10_fu_1241_p2;
wire   [1:0] grp_fu_1304_p0;
wire   [1:0] grp_fu_1313_p0;
wire   [1:0] grp_fu_1322_p0;
wire   [1:0] grp_fu_1331_p0;
wire   [1:0] grp_fu_1340_p0;
wire   [1:0] grp_fu_1349_p0;
wire   [1:0] grp_fu_1358_p0;
wire   [1:0] grp_fu_1367_p0;
wire   [1:0] grp_fu_1375_p0;
wire   [1:0] grp_fu_1384_p0;
wire   [1:0] grp_fu_1393_p0;
wire   [1:0] grp_fu_1402_p0;
wire   [1:0] grp_fu_1411_p0;
wire   [1:0] grp_fu_1420_p0;
wire   [1:0] grp_fu_1429_p0;
reg    grp_fu_1304_ce;
reg    grp_fu_1313_ce;
reg    grp_fu_1322_ce;
reg    grp_fu_1331_ce;
reg    grp_fu_1340_ce;
reg    grp_fu_1349_ce;
reg    grp_fu_1358_ce;
reg    grp_fu_1367_ce;
reg    grp_fu_1375_ce;
reg    grp_fu_1384_ce;
reg    grp_fu_1393_ce;
reg    grp_fu_1402_ce;
reg    grp_fu_1411_ce;
reg    grp_fu_1420_ce;
reg    grp_fu_1429_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg   [1:0] ap_NS_iter6_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
wire    ap_ST_iter3_fsm_state4_blk;
wire    ap_ST_iter4_fsm_state5_blk;
wire    ap_ST_iter5_fsm_state6_blk;
reg    ap_ST_iter6_fsm_state7_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] grp_fu_1304_p00;
wire   [3:0] grp_fu_1313_p00;
wire   [3:0] grp_fu_1322_p00;
wire   [3:0] grp_fu_1331_p00;
wire   [3:0] grp_fu_1340_p00;
wire   [3:0] grp_fu_1349_p00;
wire   [3:0] grp_fu_1358_p00;
wire   [3:0] grp_fu_1367_p00;
wire   [3:0] grp_fu_1375_p00;
wire   [3:0] grp_fu_1384_p00;
wire   [3:0] grp_fu_1393_p00;
wire   [3:0] grp_fu_1402_p00;
wire   [3:0] grp_fu_1411_p00;
wire   [3:0] grp_fu_1420_p00;
wire   [3:0] grp_fu_1429_p00;
wire   [3:0] mul_ln90_11_fu_1109_p00;
wire   [3:0] mul_ln90_14_fu_1125_p00;
wire   [3:0] mul_ln90_17_fu_1141_p00;
wire   [3:0] mul_ln90_1_fu_1029_p00;
wire   [3:0] mul_ln90_21_fu_1157_p00;
wire   [3:0] mul_ln90_4_fu_1045_p00;
wire   [3:0] mul_ln90_7_fu_1061_p00;
wire   [3:0] mul_ln90_8_fu_1077_p00;
wire   [3:0] mul_ln90_9_fu_1093_p00;
reg    ap_condition_144;
wire   [2:0] tmp_fu_318_p1;
wire   [2:0] tmp_fu_318_p3;
wire   [2:0] tmp_fu_318_p5;
wire   [2:0] tmp_fu_318_p7;
wire  signed [2:0] tmp_fu_318_p9;
wire  signed [2:0] tmp_fu_318_p11;
wire  signed [2:0] tmp_fu_318_p13;
wire  signed [2:0] tmp_fu_318_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
#0 ap_CS_iter6_fsm = 2'd1;
#0 sf_fu_158 = 32'd0;
#0 i_fu_162 = 17'd0;
#0 empty_fu_166 = 9'd0;
#0 inputBuf_fu_170 = 48'd0;
#0 inputBuf_1_fu_174 = 48'd0;
#0 inputBuf_2_fu_178 = 48'd0;
#0 inputBuf_3_fu_182 = 48'd0;
#0 inputBuf_4_fu_186 = 48'd0;
#0 inputBuf_5_fu_190 = 48'd0;
#0 inputBuf_6_fu_194 = 48'd0;
#0 inputBuf_7_fu_198 = 48'd0;
#0 nf_fu_202 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) MVAU_hls_3_sparsemux_17_3_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 48 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 48 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 48 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 48 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 48 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 48 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 48 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 48 ),
    .def_WIDTH( 48 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 48 ))
sparsemux_17_3_48_1_1_U1(
    .din0(inputBuf_fu_170),
    .din1(inputBuf_1_fu_174),
    .din2(inputBuf_2_fu_178),
    .din3(inputBuf_3_fu_182),
    .din4(inputBuf_4_fu_186),
    .din5(inputBuf_5_fu_190),
    .din6(inputBuf_6_fu_194),
    .din7(inputBuf_7_fu_198),
    .def(tmp_fu_318_p17),
    .sel(tmp_fu_318_p18),
    .dout(tmp_fu_318_p19)
);

MVAU_hls_3_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U2(
    .din0(mul_ln90_1_fu_1029_p0),
    .din1(local_temp_1_reg_1553_pp0_iter2_reg),
    .dout(mul_ln90_1_fu_1029_p2)
);

MVAU_hls_3_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U3(
    .din0(mul_ln90_4_fu_1045_p0),
    .din1(local_temp_4_reg_1568_pp0_iter2_reg),
    .dout(mul_ln90_4_fu_1045_p2)
);

MVAU_hls_3_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U4(
    .din0(mul_ln90_7_fu_1061_p0),
    .din1(local_temp_7_reg_1583_pp0_iter2_reg),
    .dout(mul_ln90_7_fu_1061_p2)
);

MVAU_hls_3_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U5(
    .din0(mul_ln90_8_fu_1077_p0),
    .din1(local_temp_8_reg_1588_pp0_iter2_reg),
    .dout(mul_ln90_8_fu_1077_p2)
);

MVAU_hls_3_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U6(
    .din0(mul_ln90_9_fu_1093_p0),
    .din1(local_temp_9_reg_1593_pp0_iter2_reg),
    .dout(mul_ln90_9_fu_1093_p2)
);

MVAU_hls_3_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U7(
    .din0(mul_ln90_11_fu_1109_p0),
    .din1(local_temp_11_reg_1603_pp0_iter2_reg),
    .dout(mul_ln90_11_fu_1109_p2)
);

MVAU_hls_3_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U8(
    .din0(mul_ln90_14_fu_1125_p0),
    .din1(local_temp_14_reg_1618_pp0_iter2_reg),
    .dout(mul_ln90_14_fu_1125_p2)
);

MVAU_hls_3_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U9(
    .din0(mul_ln90_17_fu_1141_p0),
    .din1(local_temp_17_reg_1633_pp0_iter2_reg),
    .dout(mul_ln90_17_fu_1141_p2)
);

MVAU_hls_3_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U10(
    .din0(mul_ln90_21_fu_1157_p0),
    .din1(local_temp_21_reg_1653_pp0_iter2_reg),
    .dout(mul_ln90_21_fu_1157_p2)
);

MVAU_hls_3_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1304_p0),
    .din1(local_temp_reg_1548),
    .din2(mul_ln90_1_fu_1029_p2),
    .ce(grp_fu_1304_ce),
    .dout(grp_fu_1304_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1313_p0),
    .din1(local_temp_3_reg_1563),
    .din2(mul_ln90_4_fu_1045_p2),
    .ce(grp_fu_1313_ce),
    .dout(grp_fu_1313_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1322_p0),
    .din1(local_temp_6_reg_1578),
    .din2(mul_ln90_7_fu_1061_p2),
    .ce(grp_fu_1322_ce),
    .dout(grp_fu_1322_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1331_p0),
    .din1(local_temp_10_reg_1598),
    .din2(mul_ln90_8_fu_1077_p2),
    .ce(grp_fu_1331_ce),
    .dout(grp_fu_1331_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1340_p0),
    .din1(local_temp_13_reg_1613),
    .din2(mul_ln90_11_fu_1109_p2),
    .ce(grp_fu_1340_ce),
    .dout(grp_fu_1340_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1349_p0),
    .din1(local_temp_16_reg_1628),
    .din2(mul_ln90_14_fu_1125_p2),
    .ce(grp_fu_1349_ce),
    .dout(grp_fu_1349_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1358_p0),
    .din1(local_temp_19_reg_1643),
    .din2(mul_ln90_17_fu_1141_p2),
    .ce(grp_fu_1358_ce),
    .dout(grp_fu_1358_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1367_p0),
    .din1(local_temp_22_reg_1658),
    .din2(mul_ln90_21_fu_1157_p2),
    .ce(grp_fu_1367_ce),
    .dout(grp_fu_1367_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1375_p0),
    .din1(local_temp_23_reg_1663),
    .din2(mul_ln90_9_fu_1093_p2),
    .ce(grp_fu_1375_ce),
    .dout(grp_fu_1375_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_5s_6_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mac_muladd_2ns_2s_5s_6_4_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1384_p0),
    .din1(local_temp_2_reg_1558_pp0_iter1_reg),
    .din2(grp_fu_1313_p3),
    .ce(grp_fu_1384_ce),
    .dout(grp_fu_1384_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_5s_6_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mac_muladd_2ns_2s_5s_6_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1393_p0),
    .din1(local_temp_5_reg_1573_pp0_iter1_reg),
    .din2(grp_fu_1322_p3),
    .ce(grp_fu_1393_ce),
    .dout(grp_fu_1393_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_5s_6_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mac_muladd_2ns_2s_5s_6_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1402_p0),
    .din1(local_temp_12_reg_1608_pp0_iter1_reg),
    .din2(grp_fu_1349_p3),
    .ce(grp_fu_1402_ce),
    .dout(grp_fu_1402_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_5s_6_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mac_muladd_2ns_2s_5s_6_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1411_p0),
    .din1(local_temp_15_reg_1623_pp0_iter1_reg),
    .din2(grp_fu_1304_p3),
    .ce(grp_fu_1411_ce),
    .dout(grp_fu_1411_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_5s_6_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mac_muladd_2ns_2s_5s_6_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1420_p0),
    .din1(local_temp_18_reg_1638_pp0_iter1_reg),
    .din2(grp_fu_1340_p3),
    .ce(grp_fu_1420_ce),
    .dout(grp_fu_1420_p3)
);

MVAU_hls_3_mac_muladd_2ns_2s_5s_6_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mac_muladd_2ns_2s_5s_6_4_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1429_p0),
    .din1(local_temp_20_reg_1648_pp0_iter1_reg),
    .din2(grp_fu_1358_p3),
    .ce(grp_fu_1429_ce),
    .dout(grp_fu_1429_p3)
);

MVAU_hls_3_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter6_fsm <= ap_ST_iter6_fsm_state0;
    end else begin
        ap_CS_iter6_fsm <= ap_NS_iter6_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)) & (1'b1 == ap_CS_iter6_fsm_state7) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)) & (1'b1 == ap_CS_iter6_fsm_state7) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_225 <= tmp_fu_318_p19;
    end else if (((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd6)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd0)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd1)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == 
    ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd2)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd3)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd4)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 
    == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd5)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd7)))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_225 <= in0_V_TDATA;
    end else if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_225 <= ap_phi_reg_pp0_iter0_inElem_reg_225;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if ((icmp_ln249_fu_272_p2 == 1'd0)) begin
            i_fu_162 <= i_2_fu_278_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_162 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if (((icmp_ln249_fu_272_p2 == 1'd0) & (icmp_ln290_fu_644_p2 == 1'd1))) begin
            nf_fu_202 <= nf_5_fu_667_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_fu_202 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_144)) begin
        if (((icmp_ln249_fu_272_p2 == 1'd0) & (icmp_ln290_fu_644_p2 == 1'd1))) begin
            sf_fu_158 <= 32'd0;
        end else if (((icmp_ln249_fu_272_p2 == 1'd0) & (icmp_ln290_fu_644_p2 == 1'd0))) begin
            sf_fu_158 <= sf_2_fu_638_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_158 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        add_ln169_20_reg_1977 <= add_ln169_20_fu_1191_p2;
        add_ln169_reg_1942 <= grp_fu_1367_p3;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        icmp_ln249_reg_1514_pp0_iter4_reg <= icmp_ln249_reg_1514_pp0_iter3_reg;
        icmp_ln272_reg_1543_pp0_iter4_reg <= icmp_ln272_reg_1543_pp0_iter3_reg;
        icmp_ln290_reg_1668_pp0_iter4_reg <= icmp_ln290_reg_1668_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_1514 <= icmp_ln249_fu_272_p2;
        icmp_ln272_reg_1543 <= icmp_ln272_fu_398_p2;
        icmp_ln290_reg_1668 <= icmp_ln290_fu_644_p2;
        local_temp_10_reg_1598 <= {{weights_V_TDATA[21:20]}};
        local_temp_11_reg_1603 <= {{weights_V_TDATA[23:22]}};
        local_temp_12_reg_1608 <= {{weights_V_TDATA[25:24]}};
        local_temp_13_reg_1613 <= {{weights_V_TDATA[27:26]}};
        local_temp_14_reg_1618 <= {{weights_V_TDATA[29:28]}};
        local_temp_15_reg_1623 <= {{weights_V_TDATA[31:30]}};
        local_temp_16_reg_1628 <= {{weights_V_TDATA[33:32]}};
        local_temp_17_reg_1633 <= {{weights_V_TDATA[35:34]}};
        local_temp_18_reg_1638 <= {{weights_V_TDATA[37:36]}};
        local_temp_19_reg_1643 <= {{weights_V_TDATA[39:38]}};
        local_temp_1_reg_1553 <= {{weights_V_TDATA[3:2]}};
        local_temp_20_reg_1648 <= {{weights_V_TDATA[41:40]}};
        local_temp_21_reg_1653 <= {{weights_V_TDATA[43:42]}};
        local_temp_22_reg_1658 <= {{weights_V_TDATA[45:44]}};
        local_temp_23_reg_1663 <= {{weights_V_TDATA[47:46]}};
        local_temp_2_reg_1558 <= {{weights_V_TDATA[5:4]}};
        local_temp_3_reg_1563 <= {{weights_V_TDATA[7:6]}};
        local_temp_4_reg_1568 <= {{weights_V_TDATA[9:8]}};
        local_temp_5_reg_1573 <= {{weights_V_TDATA[11:10]}};
        local_temp_6_reg_1578 <= {{weights_V_TDATA[13:12]}};
        local_temp_7_reg_1583 <= {{weights_V_TDATA[15:14]}};
        local_temp_8_reg_1588 <= {{weights_V_TDATA[17:16]}};
        local_temp_9_reg_1593 <= {{weights_V_TDATA[19:18]}};
        local_temp_reg_1548 <= local_temp_fu_404_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln249_reg_1514_pp0_iter1_reg <= icmp_ln249_reg_1514;
        icmp_ln272_reg_1543_pp0_iter1_reg <= icmp_ln272_reg_1543;
        icmp_ln290_reg_1668_pp0_iter1_reg <= icmp_ln290_reg_1668;
        local_temp_11_reg_1603_pp0_iter1_reg <= local_temp_11_reg_1603;
        local_temp_12_reg_1608_pp0_iter1_reg <= local_temp_12_reg_1608;
        local_temp_14_reg_1618_pp0_iter1_reg <= local_temp_14_reg_1618;
        local_temp_15_reg_1623_pp0_iter1_reg <= local_temp_15_reg_1623;
        local_temp_17_reg_1633_pp0_iter1_reg <= local_temp_17_reg_1633;
        local_temp_18_reg_1638_pp0_iter1_reg <= local_temp_18_reg_1638;
        local_temp_1_reg_1553_pp0_iter1_reg <= local_temp_1_reg_1553;
        local_temp_20_reg_1648_pp0_iter1_reg <= local_temp_20_reg_1648;
        local_temp_21_reg_1653_pp0_iter1_reg <= local_temp_21_reg_1653;
        local_temp_2_reg_1558_pp0_iter1_reg <= local_temp_2_reg_1558;
        local_temp_4_reg_1568_pp0_iter1_reg <= local_temp_4_reg_1568;
        local_temp_5_reg_1573_pp0_iter1_reg <= local_temp_5_reg_1573;
        local_temp_7_reg_1583_pp0_iter1_reg <= local_temp_7_reg_1583;
        local_temp_8_reg_1588_pp0_iter1_reg <= local_temp_8_reg_1588;
        local_temp_9_reg_1593_pp0_iter1_reg <= local_temp_9_reg_1593;
        r_11_reg_1747 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[23:22]}};
        r_12_reg_1752 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[25:24]}};
        r_14_reg_1767 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[29:28]}};
        r_15_reg_1772 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[31:30]}};
        r_17_reg_1787 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[35:34]}};
        r_18_reg_1792 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[37:36]}};
        r_1_reg_1682 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[3:2]}};
        r_20_reg_1807 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[41:40]}};
        r_21_reg_1812 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[43:42]}};
        r_2_reg_1687 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[5:4]}};
        r_4_reg_1702 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[9:8]}};
        r_5_reg_1707 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[11:10]}};
        r_7_reg_1722 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[15:14]}};
        r_8_reg_1727 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[17:16]}};
        r_9_reg_1732 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[19:18]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln249_reg_1514_pp0_iter2_reg <= icmp_ln249_reg_1514_pp0_iter1_reg;
        icmp_ln272_reg_1543_pp0_iter2_reg <= icmp_ln272_reg_1543_pp0_iter1_reg;
        icmp_ln290_reg_1668_pp0_iter2_reg <= icmp_ln290_reg_1668_pp0_iter1_reg;
        local_temp_11_reg_1603_pp0_iter2_reg <= local_temp_11_reg_1603_pp0_iter1_reg;
        local_temp_14_reg_1618_pp0_iter2_reg <= local_temp_14_reg_1618_pp0_iter1_reg;
        local_temp_17_reg_1633_pp0_iter2_reg <= local_temp_17_reg_1633_pp0_iter1_reg;
        local_temp_1_reg_1553_pp0_iter2_reg <= local_temp_1_reg_1553_pp0_iter1_reg;
        local_temp_21_reg_1653_pp0_iter2_reg <= local_temp_21_reg_1653_pp0_iter1_reg;
        local_temp_4_reg_1568_pp0_iter2_reg <= local_temp_4_reg_1568_pp0_iter1_reg;
        local_temp_7_reg_1583_pp0_iter2_reg <= local_temp_7_reg_1583_pp0_iter1_reg;
        local_temp_8_reg_1588_pp0_iter2_reg <= local_temp_8_reg_1588_pp0_iter1_reg;
        local_temp_9_reg_1593_pp0_iter2_reg <= local_temp_9_reg_1593_pp0_iter1_reg;
        r_11_reg_1747_pp0_iter2_reg <= r_11_reg_1747;
        r_14_reg_1767_pp0_iter2_reg <= r_14_reg_1767;
        r_17_reg_1787_pp0_iter2_reg <= r_17_reg_1787;
        r_1_reg_1682_pp0_iter2_reg <= r_1_reg_1682;
        r_21_reg_1812_pp0_iter2_reg <= r_21_reg_1812;
        r_4_reg_1702_pp0_iter2_reg <= r_4_reg_1702;
        r_7_reg_1722_pp0_iter2_reg <= r_7_reg_1722;
        r_8_reg_1727_pp0_iter2_reg <= r_8_reg_1727;
        r_9_reg_1732_pp0_iter2_reg <= r_9_reg_1732;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln249_reg_1514_pp0_iter3_reg <= icmp_ln249_reg_1514_pp0_iter2_reg;
        icmp_ln272_reg_1543_pp0_iter3_reg <= icmp_ln272_reg_1543_pp0_iter2_reg;
        icmp_ln290_reg_1668_pp0_iter3_reg <= icmp_ln290_reg_1668_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter5_fsm_state6) & (icmp_ln249_reg_1514_pp0_iter4_reg == 1'd0))) begin
        empty_fu_166 <= outElem_fu_1289_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        icmp_ln249_reg_1514_pp0_iter5_reg <= icmp_ln249_reg_1514_pp0_iter4_reg;
        icmp_ln290_reg_1668_pp0_iter5_reg <= icmp_ln290_reg_1668_pp0_iter4_reg;
        outElem_reg_1982 <= outElem_fu_1289_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd1))) begin
        inputBuf_1_fu_174 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd2))) begin
        inputBuf_2_fu_178 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd3))) begin
        inputBuf_3_fu_182 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd4))) begin
        inputBuf_4_fu_186 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd5))) begin
        inputBuf_5_fu_190 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd6))) begin
        inputBuf_6_fu_194 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd7))) begin
        inputBuf_7_fu_198 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (icmp_ln253_fu_288_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (trunc_ln249_fu_284_p1 == 3'd0))) begin
        inputBuf_fu_170 <= in0_V_TDATA;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

assign ap_ST_iter3_fsm_state4_blk = 1'b0;

assign ap_ST_iter4_fsm_state5_blk = 1'b0;

assign ap_ST_iter5_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) begin
        ap_ST_iter6_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_iter6_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)) & (1'b1 == ap_CS_iter6_fsm_state7) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter6_fsm_state0) & (1'b1 == ap_CS_iter5_fsm_state0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 17'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_162;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_fu_202;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_158;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)))) begin
        grp_fu_1304_ce = 1'b1;
    end else begin
        grp_fu_1304_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)))) begin
        grp_fu_1313_ce = 1'b1;
    end else begin
        grp_fu_1313_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)))) begin
        grp_fu_1322_ce = 1'b1;
    end else begin
        grp_fu_1322_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)))) begin
        grp_fu_1331_ce = 1'b1;
    end else begin
        grp_fu_1331_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)))) begin
        grp_fu_1340_ce = 1'b1;
    end else begin
        grp_fu_1340_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)))) begin
        grp_fu_1349_ce = 1'b1;
    end else begin
        grp_fu_1349_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)))) begin
        grp_fu_1358_ce = 1'b1;
    end else begin
        grp_fu_1358_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)))) begin
        grp_fu_1367_ce = 1'b1;
    end else begin
        grp_fu_1367_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)))) begin
        grp_fu_1375_ce = 1'b1;
    end else begin
        grp_fu_1375_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter5_fsm_state6)))) begin
        grp_fu_1384_ce = 1'b1;
    end else begin
        grp_fu_1384_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter5_fsm_state6)))) begin
        grp_fu_1393_ce = 1'b1;
    end else begin
        grp_fu_1393_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter5_fsm_state6)))) begin
        grp_fu_1402_ce = 1'b1;
    end else begin
        grp_fu_1402_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter5_fsm_state6)))) begin
        grp_fu_1411_ce = 1'b1;
    end else begin
        grp_fu_1411_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter5_fsm_state6)))) begin
        grp_fu_1420_ce = 1'b1;
    end else begin
        grp_fu_1420_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter5_fsm_state6)))) begin
        grp_fu_1429_ce = 1'b1;
    end else begin
        grp_fu_1429_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op51_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (ap_predicate_op51_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter6_fsm_state7) & (ap_predicate_op321_write_state7 == 1'b1))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)) & (1'b1 == ap_CS_iter6_fsm_state7) & (ap_predicate_op321_write_state7 == 1'b1))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_272_p2 == 1'd0))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b0 == ap_block_state1_pp0_stage0_iter0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b0 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b0 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter6_fsm)
        ap_ST_iter6_fsm_state7 : begin
            if ((~((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)) & (1'b0 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end else if (((~((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)) & (1'b1 == ap_CS_iter6_fsm_state7) & (icmp_ln249_reg_1514_pp0_iter5_reg == 1'd1)) | (~((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)) & (1'b1 == ap_CS_iter5_fsm_state6)))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end
        end
        ap_ST_iter6_fsm_state0 : begin
            if ((~((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter6_fsm = 'bx;
        end
    endcase
end

assign add_ln169_10_fu_1241_p2 = ($signed(sext_ln169_8_fu_1237_p1) + $signed(add_ln169_4_fu_1219_p2));

assign add_ln169_15_fu_1253_p2 = ($signed(sext_ln169_12_fu_1250_p1) + $signed(sext_ln169_10_fu_1247_p1));

assign add_ln169_1_fu_1210_p2 = ($signed(sext_ln169_1_fu_1207_p1) + $signed(select_ln272_fu_1200_p3));

assign add_ln169_20_fu_1191_p2 = ($signed(sext_ln169_17_fu_1188_p1) + $signed(sext_ln169_16_fu_1185_p1));

assign add_ln169_21_fu_1269_p2 = ($signed(sext_ln169_18_fu_1266_p1) + $signed(sext_ln169_15_fu_1263_p1));

assign add_ln169_22_fu_1279_p2 = ($signed(sext_ln169_19_fu_1275_p1) + $signed(sext_ln169_13_fu_1259_p1));

assign add_ln169_4_fu_1219_p2 = ($signed(sext_ln169_3_fu_1216_p1) + $signed(add_ln169_1_fu_1210_p2));

assign add_ln169_9_fu_1231_p2 = ($signed(sext_ln169_7_fu_1228_p1) + $signed(sext_ln169_5_fu_1225_p1));

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state0 = ap_CS_iter5_fsm[32'd0];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

assign ap_CS_iter6_fsm_state0 = ap_CS_iter6_fsm[32'd0];

assign ap_CS_iter6_fsm_state7 = ap_CS_iter6_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_272_p2 == 1'd0)) | ((ap_predicate_op51_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state7_io = ((ap_predicate_op321_write_state7 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = ((ap_predicate_op321_write_state7 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_144 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (1'b1 == ap_block_state7_pp0_stage0_iter6)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_reg_225 = 'bx;

always @ (*) begin
    ap_predicate_op321_write_state7 = ((icmp_ln290_reg_1668_pp0_iter5_reg == 1'd1) & (icmp_ln249_reg_1514_pp0_iter5_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op51_read_state1 = ((icmp_ln253_fu_288_p2 == 1'd1) & (icmp_ln249_fu_272_p2 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign grp_fu_1304_p0 = grp_fu_1304_p00;

assign grp_fu_1304_p00 = r_fu_690_p1;

assign grp_fu_1313_p0 = grp_fu_1313_p00;

assign grp_fu_1313_p00 = r_3_fu_721_p4;

assign grp_fu_1322_p0 = grp_fu_1322_p00;

assign grp_fu_1322_p00 = r_6_fu_758_p4;

assign grp_fu_1331_p0 = grp_fu_1331_p00;

assign grp_fu_1331_p00 = r_10_fu_805_p4;

assign grp_fu_1340_p0 = grp_fu_1340_p00;

assign grp_fu_1340_p00 = r_13_fu_842_p4;

assign grp_fu_1349_p0 = grp_fu_1349_p00;

assign grp_fu_1349_p00 = r_16_fu_879_p4;

assign grp_fu_1358_p0 = grp_fu_1358_p00;

assign grp_fu_1358_p00 = r_19_fu_916_p4;

assign grp_fu_1367_p0 = grp_fu_1367_p00;

assign grp_fu_1367_p00 = r_22_fu_953_p4;

assign grp_fu_1375_p0 = grp_fu_1375_p00;

assign grp_fu_1375_p00 = r_23_fu_970_p4;

assign grp_fu_1384_p0 = grp_fu_1384_p00;

assign grp_fu_1384_p00 = r_2_reg_1687;

assign grp_fu_1393_p0 = grp_fu_1393_p00;

assign grp_fu_1393_p00 = r_5_reg_1707;

assign grp_fu_1402_p0 = grp_fu_1402_p00;

assign grp_fu_1402_p00 = r_12_reg_1752;

assign grp_fu_1411_p0 = grp_fu_1411_p00;

assign grp_fu_1411_p00 = r_15_reg_1772;

assign grp_fu_1420_p0 = grp_fu_1420_p00;

assign grp_fu_1420_p00 = r_18_reg_1792;

assign grp_fu_1429_p0 = grp_fu_1429_p00;

assign grp_fu_1429_p00 = r_20_reg_1807;

assign i_2_fu_278_p2 = (ap_sig_allocacmp_i_1 + 17'd1);

assign icmp_ln249_fu_272_p2 = ((ap_sig_allocacmp_i_1 == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_288_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_398_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_644_p2 = ((sf_2_fu_638_p2 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_661_p2 = ((nf_4_fu_655_p2 == 32'd64) ? 1'b1 : 1'b0);

assign local_temp_fu_404_p1 = weights_V_TDATA[1:0];

assign mul_ln90_11_fu_1109_p0 = mul_ln90_11_fu_1109_p00;

assign mul_ln90_11_fu_1109_p00 = r_11_reg_1747_pp0_iter2_reg;

assign mul_ln90_14_fu_1125_p0 = mul_ln90_14_fu_1125_p00;

assign mul_ln90_14_fu_1125_p00 = r_14_reg_1767_pp0_iter2_reg;

assign mul_ln90_17_fu_1141_p0 = mul_ln90_17_fu_1141_p00;

assign mul_ln90_17_fu_1141_p00 = r_17_reg_1787_pp0_iter2_reg;

assign mul_ln90_1_fu_1029_p0 = mul_ln90_1_fu_1029_p00;

assign mul_ln90_1_fu_1029_p00 = r_1_reg_1682_pp0_iter2_reg;

assign mul_ln90_21_fu_1157_p0 = mul_ln90_21_fu_1157_p00;

assign mul_ln90_21_fu_1157_p00 = r_21_reg_1812_pp0_iter2_reg;

assign mul_ln90_4_fu_1045_p0 = mul_ln90_4_fu_1045_p00;

assign mul_ln90_4_fu_1045_p00 = r_4_reg_1702_pp0_iter2_reg;

assign mul_ln90_7_fu_1061_p0 = mul_ln90_7_fu_1061_p00;

assign mul_ln90_7_fu_1061_p00 = r_7_reg_1722_pp0_iter2_reg;

assign mul_ln90_8_fu_1077_p0 = mul_ln90_8_fu_1077_p00;

assign mul_ln90_8_fu_1077_p00 = r_8_reg_1727_pp0_iter2_reg;

assign mul_ln90_9_fu_1093_p0 = mul_ln90_9_fu_1093_p00;

assign mul_ln90_9_fu_1093_p00 = r_9_reg_1732_pp0_iter2_reg;

assign nf_4_fu_655_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign nf_5_fu_667_p3 = ((icmp_ln302_fu_661_p2[0:0] == 1'b1) ? 32'd0 : nf_4_fu_655_p2);

assign outElem_fu_1289_p2 = ($signed(sext_ln169_20_fu_1285_p1) + $signed(add_ln169_10_fu_1241_p2));

assign out_V_TDATA = outElem_reg_1982;

assign r_10_fu_805_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[21:20]}};

assign r_13_fu_842_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[27:26]}};

assign r_16_fu_879_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[33:32]}};

assign r_19_fu_916_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[39:38]}};

assign r_22_fu_953_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[45:44]}};

assign r_23_fu_970_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[47:46]}};

assign r_3_fu_721_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[7:6]}};

assign r_6_fu_758_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[13:12]}};

assign r_fu_690_p1 = ap_phi_reg_pp0_iter1_inElem_reg_225[1:0];

assign select_ln272_fu_1200_p3 = ((icmp_ln272_reg_1543_pp0_iter4_reg[0:0] == 1'b1) ? 9'd0 : empty_fu_166);

assign sext_ln169_10_fu_1247_p1 = grp_fu_1411_p3;

assign sext_ln169_12_fu_1250_p1 = grp_fu_1384_p3;

assign sext_ln169_13_fu_1259_p1 = $signed(add_ln169_15_fu_1253_p2);

assign sext_ln169_15_fu_1263_p1 = grp_fu_1393_p3;

assign sext_ln169_16_fu_1185_p1 = grp_fu_1331_p3;

assign sext_ln169_17_fu_1188_p1 = grp_fu_1375_p3;

assign sext_ln169_18_fu_1266_p1 = $signed(add_ln169_20_reg_1977);

assign sext_ln169_19_fu_1275_p1 = $signed(add_ln169_21_fu_1269_p2);

assign sext_ln169_1_fu_1207_p1 = add_ln169_reg_1942;

assign sext_ln169_20_fu_1285_p1 = $signed(add_ln169_22_fu_1279_p2);

assign sext_ln169_3_fu_1216_p1 = grp_fu_1429_p3;

assign sext_ln169_5_fu_1225_p1 = grp_fu_1420_p3;

assign sext_ln169_7_fu_1228_p1 = grp_fu_1402_p3;

assign sext_ln169_8_fu_1237_p1 = $signed(add_ln169_9_fu_1231_p2);

assign sf_2_fu_638_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign tmp_fu_318_p17 = 'bx;

assign tmp_fu_318_p18 = ap_sig_allocacmp_sf_1[2:0];

assign trunc_ln249_fu_284_p1 = ap_sig_allocacmp_sf_1[2:0];

endmodule //MVAU_hls_3_Matrix_Vector_Activate_Stream_Batch
