// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module LabelSelect_hls_0_LabelSelect_hls_0_Pipeline_VITIS_LOOP_488_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        in0_V_TDATA,
        in0_V_TREADY,
        select_ln509_1_out,
        select_ln509_1_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input  [15:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] select_ln509_1_out;
output   select_ln509_1_out_ap_vld;

reg ap_idle;
reg in0_V_TREADY;
reg select_ln509_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln488_fu_130_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg   [9:0] part_select_i_i_i15_i1_fu_44;
wire   [9:0] select_ln509_fu_107_p3;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_part_select_i_i_i15_i1_load;
reg   [7:0] arrayidx77_0_0_0_load12_i3_fu_48;
wire   [7:0] select_ln509_1_fu_115_p3;
reg   [7:0] ap_sig_allocacmp_arrayidx77_0_0_0_load;
reg   [3:0] block_14_fu_52;
wire   [3:0] block_fu_124_p2;
reg   [3:0] ap_sig_allocacmp_block_14_load;
wire   [9:0] inval_fu_93_p1;
wire   [0:0] cmp_fu_97_p2;
wire   [7:0] conv2_i_i_i_fu_103_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 part_select_i_i_i15_i1_fu_44 = 10'd0;
#0 arrayidx77_0_0_0_load12_i3_fu_48 = 8'd0;
#0 block_14_fu_52 = 4'd0;
#0 ap_done_reg = 1'b0;
end

LabelSelect_hls_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        arrayidx77_0_0_0_load12_i3_fu_48 <= select_ln509_1_fu_115_p3;
    end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
    block_14_fu_52 <= block_fu_124_p2;
end
end

always @ (posedge ap_clk) begin
if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
    part_select_i_i_i15_i1_fu_44 <= select_ln509_fu_107_p3;
end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln488_fu_130_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_arrayidx77_0_0_0_load = 8'd0;
    end else begin
        ap_sig_allocacmp_arrayidx77_0_0_0_load = arrayidx77_0_0_0_load12_i3_fu_48;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_block_14_load = 4'd0;
    end else begin
        ap_sig_allocacmp_block_14_load = block_14_fu_52;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_part_select_i_i_i15_i1_load = 10'd512;
    end else begin
        ap_sig_allocacmp_part_select_i_i_i15_i1_load = part_select_i_i_i15_i1_fu_44;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln488_fu_130_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        select_ln509_1_out_ap_vld = 1'b1;
    end else begin
        select_ln509_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((in0_V_TVALID == 1'b0) | (ap_start_int == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign block_fu_124_p2 = (ap_sig_allocacmp_block_14_load + 4'd1);

assign cmp_fu_97_p2 = (($signed(inval_fu_93_p1) > $signed(ap_sig_allocacmp_part_select_i_i_i15_i1_load)) ? 1'b1 : 1'b0);

assign conv2_i_i_i_fu_103_p1 = ap_sig_allocacmp_block_14_load;

assign icmp_ln488_fu_130_p2 = ((ap_sig_allocacmp_block_14_load == 4'd14) ? 1'b1 : 1'b0);

assign inval_fu_93_p1 = in0_V_TDATA[9:0];

assign select_ln509_1_fu_115_p3 = ((cmp_fu_97_p2[0:0] == 1'b1) ? conv2_i_i_i_fu_103_p1 : ap_sig_allocacmp_arrayidx77_0_0_0_load);

assign select_ln509_1_out = ((cmp_fu_97_p2[0:0] == 1'b1) ? conv2_i_i_i_fu_103_p1 : ap_sig_allocacmp_arrayidx77_0_0_0_load);

assign select_ln509_fu_107_p3 = ((cmp_fu_97_p2[0:0] == 1'b1) ? inval_fu_93_p1 : ap_sig_allocacmp_part_select_i_i_i15_i1_load);

endmodule //LabelSelect_hls_0_LabelSelect_hls_0_Pipeline_VITIS_LOOP_488_3
