// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MVAU_hls_5_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [15:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [15:0] out_V_TDATA;
output   out_V_TVALID;
input  [15:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
wire   [0:0] icmp_ln249_fu_396_p2;
wire   [0:0] icmp_ln253_fu_412_p2;
reg    ap_predicate_op97_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] icmp_ln249_reg_1347;
reg   [0:0] icmp_ln249_reg_1347_pp0_iter3_reg;
reg   [0:0] icmp_ln290_reg_1435;
reg   [0:0] icmp_ln290_reg_1435_pp0_iter3_reg;
reg    ap_predicate_op236_write_state5;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_state5_io;
wire    ap_CS_iter4_fsm_state5;
reg    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [0:0] icmp_ln249_reg_1347_pp0_iter1_reg;
reg   [0:0] icmp_ln249_reg_1347_pp0_iter2_reg;
wire   [4:0] trunc_ln249_fu_408_p1;
wire   [11:0] tmp_fu_514_p67;
wire   [11:0] inputBuf_32_fu_650_p1;
wire   [0:0] icmp_ln272_fu_814_p2;
reg   [0:0] icmp_ln272_reg_1400;
reg   [0:0] icmp_ln272_reg_1400_pp0_iter1_reg;
reg   [0:0] icmp_ln272_reg_1400_pp0_iter2_reg;
reg   [0:0] icmp_ln272_reg_1400_pp0_iter3_reg;
wire   [1:0] local_temp_fu_820_p1;
reg   [1:0] local_temp_reg_1405;
reg   [1:0] local_temp_reg_1405_pp0_iter1_reg;
reg  signed [1:0] local_temp_reg_1405_pp0_iter2_reg;
reg  signed [1:0] local_temp_1_reg_1410;
reg   [1:0] local_temp_2_reg_1415;
reg   [1:0] local_temp_2_reg_1415_pp0_iter1_reg;
reg  signed [1:0] local_temp_2_reg_1415_pp0_iter2_reg;
reg   [1:0] local_temp_3_reg_1420;
reg   [1:0] local_temp_3_reg_1420_pp0_iter1_reg;
reg  signed [1:0] local_temp_3_reg_1420_pp0_iter2_reg;
reg  signed [1:0] local_temp_4_reg_1425;
reg  signed [1:0] local_temp_5_reg_1430;
wire   [0:0] icmp_ln290_fu_880_p2;
reg   [0:0] icmp_ln290_reg_1435_pp0_iter1_reg;
reg   [0:0] icmp_ln290_reg_1435_pp0_iter2_reg;
wire   [1:0] r_fu_926_p1;
reg   [1:0] r_reg_1439;
reg   [1:0] r_reg_1439_pp0_iter2_reg;
reg   [1:0] r_2_reg_1454;
reg   [1:0] r_2_reg_1454_pp0_iter2_reg;
reg   [1:0] r_3_reg_1459;
reg   [1:0] r_3_reg_1459_pp0_iter2_reg;
wire   [11:0] ap_phi_reg_pp0_iter0_inElem_reg_301;
reg   [11:0] ap_phi_reg_pp0_iter1_inElem_reg_301;
reg   [31:0] sf_fu_138;
wire   [31:0] sf_2_fu_874_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [16:0] i_fu_142;
wire   [16:0] i_2_fu_402_p2;
reg   [16:0] ap_sig_allocacmp_i_1;
reg   [8:0] empty_fu_146;
wire   [8:0] outElem_fu_1084_p2;
reg   [11:0] inputBuf_fu_150;
reg   [11:0] inputBuf_1_fu_154;
reg   [11:0] inputBuf_2_fu_158;
reg   [11:0] inputBuf_3_fu_162;
reg   [11:0] inputBuf_4_fu_166;
reg   [11:0] inputBuf_5_fu_170;
reg   [11:0] inputBuf_6_fu_174;
reg   [11:0] inputBuf_7_fu_178;
reg   [11:0] inputBuf_8_fu_182;
reg   [11:0] inputBuf_9_fu_186;
reg   [11:0] inputBuf_10_fu_190;
reg   [11:0] inputBuf_11_fu_194;
reg   [11:0] inputBuf_12_fu_198;
reg   [11:0] inputBuf_13_fu_202;
reg   [11:0] inputBuf_14_fu_206;
reg   [11:0] inputBuf_15_fu_210;
reg   [11:0] inputBuf_16_fu_214;
reg   [11:0] inputBuf_17_fu_218;
reg   [11:0] inputBuf_18_fu_222;
reg   [11:0] inputBuf_19_fu_226;
reg   [11:0] inputBuf_20_fu_230;
reg   [11:0] inputBuf_21_fu_234;
reg   [11:0] inputBuf_22_fu_238;
reg   [11:0] inputBuf_23_fu_242;
reg   [11:0] inputBuf_24_fu_246;
reg   [11:0] inputBuf_25_fu_250;
reg   [11:0] inputBuf_26_fu_254;
reg   [11:0] inputBuf_27_fu_258;
reg   [11:0] inputBuf_28_fu_262;
reg   [11:0] inputBuf_29_fu_266;
reg   [11:0] inputBuf_30_fu_270;
reg   [11:0] inputBuf_31_fu_274;
reg   [31:0] nf_fu_278;
wire   [31:0] nf_5_fu_903_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [11:0] tmp_fu_514_p65;
wire   [4:0] tmp_fu_514_p66;
wire   [31:0] nf_4_fu_891_p2;
wire   [0:0] icmp_ln302_fu_897_p2;
wire   [1:0] r_1_fu_930_p4;
wire   [1:0] r_4_fu_967_p4;
wire   [1:0] r_5_fu_984_p4;
wire   [1:0] mul_ln90_fu_1007_p0;
wire  signed [3:0] mul_ln90_fu_1007_p2;
wire   [1:0] mul_ln90_2_fu_1023_p0;
wire  signed [3:0] mul_ln90_2_fu_1023_p2;
wire   [1:0] mul_ln90_3_fu_1039_p0;
wire  signed [3:0] mul_ln90_3_fu_1039_p2;
wire  signed [4:0] grp_fu_1109_p3;
wire  signed [8:0] sext_ln169_1_fu_1059_p1;
wire   [8:0] select_ln272_fu_1052_p3;
wire  signed [4:0] grp_fu_1100_p3;
wire  signed [4:0] grp_fu_1118_p3;
wire  signed [5:0] sext_ln169_3_fu_1071_p1;
wire  signed [5:0] sext_ln169_2_fu_1068_p1;
wire   [5:0] add_ln169_4_fu_1074_p2;
wire  signed [8:0] sext_ln169_4_fu_1080_p1;
wire   [8:0] add_ln169_1_fu_1062_p2;
wire   [1:0] grp_fu_1100_p0;
wire   [1:0] grp_fu_1109_p0;
wire   [1:0] grp_fu_1118_p0;
reg    grp_fu_1100_ce;
reg    grp_fu_1109_ce;
reg    grp_fu_1118_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
reg    ap_ST_iter4_fsm_state5_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] grp_fu_1100_p00;
wire   [3:0] grp_fu_1109_p00;
wire   [3:0] grp_fu_1118_p00;
wire   [3:0] mul_ln90_2_fu_1023_p00;
wire   [3:0] mul_ln90_3_fu_1039_p00;
wire   [3:0] mul_ln90_fu_1007_p00;
reg    ap_condition_131;
wire   [4:0] tmp_fu_514_p1;
wire   [4:0] tmp_fu_514_p3;
wire   [4:0] tmp_fu_514_p5;
wire   [4:0] tmp_fu_514_p7;
wire   [4:0] tmp_fu_514_p9;
wire   [4:0] tmp_fu_514_p11;
wire   [4:0] tmp_fu_514_p13;
wire   [4:0] tmp_fu_514_p15;
wire   [4:0] tmp_fu_514_p17;
wire   [4:0] tmp_fu_514_p19;
wire   [4:0] tmp_fu_514_p21;
wire   [4:0] tmp_fu_514_p23;
wire   [4:0] tmp_fu_514_p25;
wire   [4:0] tmp_fu_514_p27;
wire   [4:0] tmp_fu_514_p29;
wire   [4:0] tmp_fu_514_p31;
wire  signed [4:0] tmp_fu_514_p33;
wire  signed [4:0] tmp_fu_514_p35;
wire  signed [4:0] tmp_fu_514_p37;
wire  signed [4:0] tmp_fu_514_p39;
wire  signed [4:0] tmp_fu_514_p41;
wire  signed [4:0] tmp_fu_514_p43;
wire  signed [4:0] tmp_fu_514_p45;
wire  signed [4:0] tmp_fu_514_p47;
wire  signed [4:0] tmp_fu_514_p49;
wire  signed [4:0] tmp_fu_514_p51;
wire  signed [4:0] tmp_fu_514_p53;
wire  signed [4:0] tmp_fu_514_p55;
wire  signed [4:0] tmp_fu_514_p57;
wire  signed [4:0] tmp_fu_514_p59;
wire  signed [4:0] tmp_fu_514_p61;
wire  signed [4:0] tmp_fu_514_p63;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 sf_fu_138 = 32'd0;
#0 i_fu_142 = 17'd0;
#0 empty_fu_146 = 9'd0;
#0 inputBuf_fu_150 = 12'd0;
#0 inputBuf_1_fu_154 = 12'd0;
#0 inputBuf_2_fu_158 = 12'd0;
#0 inputBuf_3_fu_162 = 12'd0;
#0 inputBuf_4_fu_166 = 12'd0;
#0 inputBuf_5_fu_170 = 12'd0;
#0 inputBuf_6_fu_174 = 12'd0;
#0 inputBuf_7_fu_178 = 12'd0;
#0 inputBuf_8_fu_182 = 12'd0;
#0 inputBuf_9_fu_186 = 12'd0;
#0 inputBuf_10_fu_190 = 12'd0;
#0 inputBuf_11_fu_194 = 12'd0;
#0 inputBuf_12_fu_198 = 12'd0;
#0 inputBuf_13_fu_202 = 12'd0;
#0 inputBuf_14_fu_206 = 12'd0;
#0 inputBuf_15_fu_210 = 12'd0;
#0 inputBuf_16_fu_214 = 12'd0;
#0 inputBuf_17_fu_218 = 12'd0;
#0 inputBuf_18_fu_222 = 12'd0;
#0 inputBuf_19_fu_226 = 12'd0;
#0 inputBuf_20_fu_230 = 12'd0;
#0 inputBuf_21_fu_234 = 12'd0;
#0 inputBuf_22_fu_238 = 12'd0;
#0 inputBuf_23_fu_242 = 12'd0;
#0 inputBuf_24_fu_246 = 12'd0;
#0 inputBuf_25_fu_250 = 12'd0;
#0 inputBuf_26_fu_254 = 12'd0;
#0 inputBuf_27_fu_258 = 12'd0;
#0 inputBuf_28_fu_262 = 12'd0;
#0 inputBuf_29_fu_266 = 12'd0;
#0 inputBuf_30_fu_270 = 12'd0;
#0 inputBuf_31_fu_274 = 12'd0;
#0 nf_fu_278 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) MVAU_hls_5_sparsemux_65_5_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 12 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 12 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 12 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 12 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 12 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 12 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 12 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 12 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 12 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 12 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 12 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 12 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 12 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 12 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 12 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 12 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 12 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 12 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 12 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 12 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 12 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 12 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 12 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 12 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 12 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 12 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 12 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 12 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 12 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 12 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
sparsemux_65_5_12_1_1_U1(
    .din0(inputBuf_fu_150),
    .din1(inputBuf_1_fu_154),
    .din2(inputBuf_2_fu_158),
    .din3(inputBuf_3_fu_162),
    .din4(inputBuf_4_fu_166),
    .din5(inputBuf_5_fu_170),
    .din6(inputBuf_6_fu_174),
    .din7(inputBuf_7_fu_178),
    .din8(inputBuf_8_fu_182),
    .din9(inputBuf_9_fu_186),
    .din10(inputBuf_10_fu_190),
    .din11(inputBuf_11_fu_194),
    .din12(inputBuf_12_fu_198),
    .din13(inputBuf_13_fu_202),
    .din14(inputBuf_14_fu_206),
    .din15(inputBuf_15_fu_210),
    .din16(inputBuf_16_fu_214),
    .din17(inputBuf_17_fu_218),
    .din18(inputBuf_18_fu_222),
    .din19(inputBuf_19_fu_226),
    .din20(inputBuf_20_fu_230),
    .din21(inputBuf_21_fu_234),
    .din22(inputBuf_22_fu_238),
    .din23(inputBuf_23_fu_242),
    .din24(inputBuf_24_fu_246),
    .din25(inputBuf_25_fu_250),
    .din26(inputBuf_26_fu_254),
    .din27(inputBuf_27_fu_258),
    .din28(inputBuf_28_fu_262),
    .din29(inputBuf_29_fu_266),
    .din30(inputBuf_30_fu_270),
    .din31(inputBuf_31_fu_274),
    .def(tmp_fu_514_p65),
    .sel(tmp_fu_514_p66),
    .dout(tmp_fu_514_p67)
);

MVAU_hls_5_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U2(
    .din0(mul_ln90_fu_1007_p0),
    .din1(local_temp_reg_1405_pp0_iter2_reg),
    .dout(mul_ln90_fu_1007_p2)
);

MVAU_hls_5_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U3(
    .din0(mul_ln90_2_fu_1023_p0),
    .din1(local_temp_2_reg_1415_pp0_iter2_reg),
    .dout(mul_ln90_2_fu_1023_p2)
);

MVAU_hls_5_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U4(
    .din0(mul_ln90_3_fu_1039_p0),
    .din1(local_temp_3_reg_1420_pp0_iter2_reg),
    .dout(mul_ln90_3_fu_1039_p2)
);

MVAU_hls_5_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1100_p0),
    .din1(local_temp_1_reg_1410),
    .din2(mul_ln90_2_fu_1023_p2),
    .ce(grp_fu_1100_ce),
    .dout(grp_fu_1100_p3)
);

MVAU_hls_5_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1109_p0),
    .din1(local_temp_4_reg_1425),
    .din2(mul_ln90_3_fu_1039_p2),
    .ce(grp_fu_1109_ce),
    .dout(grp_fu_1109_p3)
);

MVAU_hls_5_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1118_p0),
    .din1(local_temp_5_reg_1430),
    .din2(mul_ln90_fu_1007_p2),
    .ce(grp_fu_1118_ce),
    .dout(grp_fu_1118_p3)
);

MVAU_hls_5_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_301 <= tmp_fu_514_p67;
    end else if (((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd30)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd0)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) 
    | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd1)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd2)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) 
    & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd3)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd4)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 
    == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd5)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd6)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 
    == 5'd7)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd8)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd9)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 
    == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd10)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd11)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) 
    | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd12)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd13)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) 
    & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd14)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd15)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 
    1'd0) & (trunc_ln249_fu_408_p1 == 5'd16)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd17)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd18)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 
    == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd19)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd20)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) 
    & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd21)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd22)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) 
    | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd23)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd24)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) 
    & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd25)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd26)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd27)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) 
    | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd28)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd29)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) 
    & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd31)))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_301 <= inputBuf_32_fu_650_p1;
    end else if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_301 <= ap_phi_reg_pp0_iter0_inElem_reg_301;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_131)) begin
        if ((icmp_ln249_fu_396_p2 == 1'd0)) begin
            i_fu_142 <= i_2_fu_402_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_142 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_131)) begin
        if (((icmp_ln249_fu_396_p2 == 1'd0) & (icmp_ln290_fu_880_p2 == 1'd1))) begin
            nf_fu_278 <= nf_5_fu_903_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_fu_278 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_131)) begin
        if (((icmp_ln249_fu_396_p2 == 1'd0) & (icmp_ln290_fu_880_p2 == 1'd1))) begin
            sf_fu_138 <= 32'd0;
        end else if (((icmp_ln249_fu_396_p2 == 1'd0) & (icmp_ln290_fu_880_p2 == 1'd0))) begin
            sf_fu_138 <= sf_2_fu_874_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_138 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_1347 <= icmp_ln249_fu_396_p2;
        icmp_ln272_reg_1400 <= icmp_ln272_fu_814_p2;
        icmp_ln290_reg_1435 <= icmp_ln290_fu_880_p2;
        local_temp_1_reg_1410 <= {{weights_V_TDATA[3:2]}};
        local_temp_2_reg_1415 <= {{weights_V_TDATA[5:4]}};
        local_temp_3_reg_1420 <= {{weights_V_TDATA[7:6]}};
        local_temp_4_reg_1425 <= {{weights_V_TDATA[9:8]}};
        local_temp_5_reg_1430 <= {{weights_V_TDATA[11:10]}};
        local_temp_reg_1405 <= local_temp_fu_820_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln249_reg_1347_pp0_iter1_reg <= icmp_ln249_reg_1347;
        icmp_ln272_reg_1400_pp0_iter1_reg <= icmp_ln272_reg_1400;
        icmp_ln290_reg_1435_pp0_iter1_reg <= icmp_ln290_reg_1435;
        local_temp_2_reg_1415_pp0_iter1_reg <= local_temp_2_reg_1415;
        local_temp_3_reg_1420_pp0_iter1_reg <= local_temp_3_reg_1420;
        local_temp_reg_1405_pp0_iter1_reg <= local_temp_reg_1405;
        r_2_reg_1454 <= {{ap_phi_reg_pp0_iter1_inElem_reg_301[5:4]}};
        r_3_reg_1459 <= {{ap_phi_reg_pp0_iter1_inElem_reg_301[7:6]}};
        r_reg_1439 <= r_fu_926_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln249_reg_1347_pp0_iter2_reg <= icmp_ln249_reg_1347_pp0_iter1_reg;
        icmp_ln272_reg_1400_pp0_iter2_reg <= icmp_ln272_reg_1400_pp0_iter1_reg;
        icmp_ln290_reg_1435_pp0_iter2_reg <= icmp_ln290_reg_1435_pp0_iter1_reg;
        local_temp_2_reg_1415_pp0_iter2_reg <= local_temp_2_reg_1415_pp0_iter1_reg;
        local_temp_3_reg_1420_pp0_iter2_reg <= local_temp_3_reg_1420_pp0_iter1_reg;
        local_temp_reg_1405_pp0_iter2_reg <= local_temp_reg_1405_pp0_iter1_reg;
        r_2_reg_1454_pp0_iter2_reg <= r_2_reg_1454;
        r_3_reg_1459_pp0_iter2_reg <= r_3_reg_1459;
        r_reg_1439_pp0_iter2_reg <= r_reg_1439;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (icmp_ln249_reg_1347_pp0_iter3_reg == 1'd0) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        empty_fu_146 <= outElem_fu_1084_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        icmp_ln249_reg_1347_pp0_iter3_reg <= icmp_ln249_reg_1347_pp0_iter2_reg;
        icmp_ln272_reg_1400_pp0_iter3_reg <= icmp_ln272_reg_1400_pp0_iter2_reg;
        icmp_ln290_reg_1435_pp0_iter3_reg <= icmp_ln290_reg_1435_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd10))) begin
        inputBuf_10_fu_190 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd11))) begin
        inputBuf_11_fu_194 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd12))) begin
        inputBuf_12_fu_198 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd13))) begin
        inputBuf_13_fu_202 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd14))) begin
        inputBuf_14_fu_206 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd15))) begin
        inputBuf_15_fu_210 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd16))) begin
        inputBuf_16_fu_214 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd17))) begin
        inputBuf_17_fu_218 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd18))) begin
        inputBuf_18_fu_222 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd19))) begin
        inputBuf_19_fu_226 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd1))) begin
        inputBuf_1_fu_154 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd20))) begin
        inputBuf_20_fu_230 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd21))) begin
        inputBuf_21_fu_234 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd22))) begin
        inputBuf_22_fu_238 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd23))) begin
        inputBuf_23_fu_242 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd24))) begin
        inputBuf_24_fu_246 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd25))) begin
        inputBuf_25_fu_250 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd26))) begin
        inputBuf_26_fu_254 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd27))) begin
        inputBuf_27_fu_258 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd28))) begin
        inputBuf_28_fu_262 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd29))) begin
        inputBuf_29_fu_266 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd2))) begin
        inputBuf_2_fu_158 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd30))) begin
        inputBuf_30_fu_270 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd31))) begin
        inputBuf_31_fu_274 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd3))) begin
        inputBuf_3_fu_162 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd4))) begin
        inputBuf_4_fu_166 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd5))) begin
        inputBuf_5_fu_170 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd6))) begin
        inputBuf_6_fu_174 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd7))) begin
        inputBuf_7_fu_178 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd8))) begin
        inputBuf_8_fu_182 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd9))) begin
        inputBuf_9_fu_186 <= inputBuf_32_fu_650_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (icmp_ln253_fu_412_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0) & (trunc_ln249_fu_408_p1 == 5'd0))) begin
        inputBuf_fu_150 <= inputBuf_32_fu_650_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_pp0_stage0_iter2)) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4_pp0_stage0_iter3)) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4))) begin
        ap_ST_iter4_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_iter4_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 17'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_142;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_fu_278;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_138;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_1100_ce = 1'b1;
    end else begin
        grp_fu_1100_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_1109_ce = 1'b1;
    end else begin
        grp_fu_1109_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_1118_ce = 1'b1;
    end else begin
        grp_fu_1118_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_predicate_op97_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (ap_predicate_op97_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op236_write_state5 == 1'b1) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (ap_predicate_op236_write_state5 == 1'b1) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_396_p2 == 1'd0))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b0 == ap_block_state3_pp0_stage0_iter2) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & ((1'b0 == ap_CS_iter2_fsm_state3) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & ((1'b0 == ap_CS_iter3_fsm_state4) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3))))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else if (((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (icmp_ln249_reg_1347_pp0_iter3_reg == 1'd1) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)) & (1'b0 == ap_block_state4_pp0_stage0_iter3) & (1'b1 == ap_CS_iter3_fsm_state4)))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

assign add_ln169_1_fu_1062_p2 = ($signed(sext_ln169_1_fu_1059_p1) + $signed(select_ln272_fu_1052_p3));

assign add_ln169_4_fu_1074_p2 = ($signed(sext_ln169_3_fu_1071_p1) + $signed(sext_ln169_2_fu_1068_p1));

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_396_p2 == 1'd0)) | ((ap_predicate_op97_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)));
end

always @ (*) begin
    ap_block_state5_io = ((ap_predicate_op236_write_state5 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((ap_predicate_op236_write_state5 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_131 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage0_iter4)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_reg_301 = 'bx;

always @ (*) begin
    ap_predicate_op236_write_state5 = ((icmp_ln290_reg_1435_pp0_iter3_reg == 1'd1) & (icmp_ln249_reg_1347_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op97_read_state1 = ((icmp_ln253_fu_412_p2 == 1'd1) & (icmp_ln249_fu_396_p2 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign grp_fu_1100_p0 = grp_fu_1100_p00;

assign grp_fu_1100_p00 = r_1_fu_930_p4;

assign grp_fu_1109_p0 = grp_fu_1109_p00;

assign grp_fu_1109_p00 = r_4_fu_967_p4;

assign grp_fu_1118_p0 = grp_fu_1118_p00;

assign grp_fu_1118_p00 = r_5_fu_984_p4;

assign i_2_fu_402_p2 = (ap_sig_allocacmp_i_1 + 17'd1);

assign icmp_ln249_fu_396_p2 = ((ap_sig_allocacmp_i_1 == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_412_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_814_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_880_p2 = ((sf_2_fu_874_p2 == 32'd32) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_897_p2 = ((nf_4_fu_891_p2 == 32'd64) ? 1'b1 : 1'b0);

assign inputBuf_32_fu_650_p1 = in0_V_TDATA[11:0];

assign local_temp_fu_820_p1 = weights_V_TDATA[1:0];

assign mul_ln90_2_fu_1023_p0 = mul_ln90_2_fu_1023_p00;

assign mul_ln90_2_fu_1023_p00 = r_2_reg_1454_pp0_iter2_reg;

assign mul_ln90_3_fu_1039_p0 = mul_ln90_3_fu_1039_p00;

assign mul_ln90_3_fu_1039_p00 = r_3_reg_1459_pp0_iter2_reg;

assign mul_ln90_fu_1007_p0 = mul_ln90_fu_1007_p00;

assign mul_ln90_fu_1007_p00 = r_reg_1439_pp0_iter2_reg;

assign nf_4_fu_891_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign nf_5_fu_903_p3 = ((icmp_ln302_fu_897_p2[0:0] == 1'b1) ? 32'd0 : nf_4_fu_891_p2);

assign outElem_fu_1084_p2 = ($signed(sext_ln169_4_fu_1080_p1) + $signed(add_ln169_1_fu_1062_p2));

assign out_V_TDATA = outElem_fu_1084_p2;

assign r_1_fu_930_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_301[3:2]}};

assign r_4_fu_967_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_301[9:8]}};

assign r_5_fu_984_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_301[11:10]}};

assign r_fu_926_p1 = ap_phi_reg_pp0_iter1_inElem_reg_301[1:0];

assign select_ln272_fu_1052_p3 = ((icmp_ln272_reg_1400_pp0_iter3_reg[0:0] == 1'b1) ? 9'd0 : empty_fu_146);

assign sext_ln169_1_fu_1059_p1 = grp_fu_1109_p3;

assign sext_ln169_2_fu_1068_p1 = grp_fu_1100_p3;

assign sext_ln169_3_fu_1071_p1 = grp_fu_1118_p3;

assign sext_ln169_4_fu_1080_p1 = $signed(add_ln169_4_fu_1074_p2);

assign sf_2_fu_874_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign tmp_fu_514_p65 = 'bx;

assign tmp_fu_514_p66 = ap_sig_allocacmp_sf_1[4:0];

assign trunc_ln249_fu_408_p1 = ap_sig_allocacmp_sf_1[4:0];

endmodule //MVAU_hls_5_Matrix_Vector_Activate_Stream_Batch
