// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MVAU_hls_4_Matrix_Vector_Activate_Stream_Batch (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        weights_V_TDATA,
        weights_V_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [23:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [15:0] out_V_TDATA;
output   out_V_TVALID;
input  [23:0] weights_V_TDATA;
output   weights_V_TREADY;

reg ap_idle;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
reg   [1:0] ap_CS_iter5_fsm;
wire    ap_CS_iter5_fsm_state0;
wire   [0:0] icmp_ln249_fu_288_p2;
wire   [0:0] icmp_ln253_fu_304_p2;
reg    ap_predicate_op66_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] icmp_ln249_reg_1187;
reg   [0:0] icmp_ln249_reg_1187_pp0_iter4_reg;
reg   [0:0] icmp_ln290_reg_1289;
reg   [0:0] icmp_ln290_reg_1289_pp0_iter4_reg;
reg    ap_predicate_op231_write_state6;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_state6_io;
wire    ap_CS_iter5_fsm_state6;
reg    ap_block_state5_pp0_stage0_iter4;
wire    ap_CS_iter4_fsm_state5;
reg    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg   [0:0] icmp_ln249_reg_1187_pp0_iter1_reg;
reg   [0:0] icmp_ln249_reg_1187_pp0_iter2_reg;
reg   [0:0] icmp_ln249_reg_1187_pp0_iter3_reg;
wire   [3:0] trunc_ln249_fu_300_p1;
wire   [23:0] tmp_fu_358_p35;
wire   [0:0] icmp_ln272_fu_510_p2;
reg   [0:0] icmp_ln272_reg_1224;
reg   [0:0] icmp_ln272_reg_1224_pp0_iter1_reg;
reg   [0:0] icmp_ln272_reg_1224_pp0_iter2_reg;
reg   [0:0] icmp_ln272_reg_1224_pp0_iter3_reg;
reg   [0:0] icmp_ln272_reg_1224_pp0_iter4_reg;
wire   [1:0] local_temp_fu_516_p1;
reg  signed [1:0] local_temp_reg_1229;
reg   [1:0] local_temp_1_reg_1234;
reg   [1:0] local_temp_1_reg_1234_pp0_iter1_reg;
reg  signed [1:0] local_temp_1_reg_1234_pp0_iter2_reg;
reg   [1:0] local_temp_2_reg_1239;
reg   [1:0] local_temp_2_reg_1239_pp0_iter1_reg;
reg  signed [1:0] local_temp_2_reg_1239_pp0_iter2_reg;
reg   [1:0] local_temp_3_reg_1244;
reg   [1:0] local_temp_3_reg_1244_pp0_iter1_reg;
reg  signed [1:0] local_temp_3_reg_1244_pp0_iter2_reg;
reg  signed [1:0] local_temp_4_reg_1249;
reg   [1:0] local_temp_5_reg_1254;
reg   [1:0] local_temp_5_reg_1254_pp0_iter1_reg;
reg  signed [1:0] local_temp_5_reg_1254_pp0_iter2_reg;
reg   [1:0] local_temp_6_reg_1259;
reg  signed [1:0] local_temp_6_reg_1259_pp0_iter1_reg;
reg  signed [1:0] local_temp_7_reg_1264;
reg   [1:0] local_temp_8_reg_1269;
reg  signed [1:0] local_temp_8_reg_1269_pp0_iter1_reg;
reg   [1:0] local_temp_9_reg_1274;
reg   [1:0] local_temp_9_reg_1274_pp0_iter1_reg;
reg  signed [1:0] local_temp_9_reg_1274_pp0_iter2_reg;
reg  signed [1:0] local_temp_10_reg_1279;
reg  signed [1:0] local_temp_11_reg_1284;
wire   [0:0] icmp_ln290_fu_636_p2;
reg   [0:0] icmp_ln290_reg_1289_pp0_iter1_reg;
reg   [0:0] icmp_ln290_reg_1289_pp0_iter2_reg;
reg   [0:0] icmp_ln290_reg_1289_pp0_iter3_reg;
reg   [1:0] r_1_reg_1303;
reg   [1:0] r_1_reg_1303_pp0_iter2_reg;
reg   [1:0] r_2_reg_1308;
reg   [1:0] r_2_reg_1308_pp0_iter2_reg;
reg   [1:0] r_3_reg_1313;
reg   [1:0] r_3_reg_1313_pp0_iter2_reg;
reg   [1:0] r_5_reg_1328;
reg   [1:0] r_5_reg_1328_pp0_iter2_reg;
reg   [1:0] r_6_reg_1333;
reg   [1:0] r_8_reg_1348;
reg   [1:0] r_9_reg_1353;
reg   [1:0] r_9_reg_1353_pp0_iter2_reg;
wire  signed [4:0] grp_fu_1028_p3;
reg  signed [4:0] add_ln169_reg_1423;
wire   [5:0] add_ln169_9_fu_935_p2;
reg   [5:0] add_ln169_9_reg_1438;
wire   [23:0] ap_phi_reg_pp0_iter0_inElem_reg_225;
reg   [23:0] ap_phi_reg_pp0_iter1_inElem_reg_225;
reg   [31:0] sf_fu_126;
wire   [31:0] sf_2_fu_630_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_sf_1;
reg   [16:0] i_fu_130;
wire   [16:0] i_2_fu_294_p2;
reg   [16:0] ap_sig_allocacmp_i_1;
reg   [8:0] empty_fu_134;
wire   [8:0] outElem_fu_985_p2;
reg   [23:0] inputBuf_fu_138;
reg   [23:0] inputBuf_1_fu_142;
reg   [23:0] inputBuf_2_fu_146;
reg   [23:0] inputBuf_3_fu_150;
reg   [23:0] inputBuf_4_fu_154;
reg   [23:0] inputBuf_5_fu_158;
reg   [23:0] inputBuf_6_fu_162;
reg   [23:0] inputBuf_7_fu_166;
reg   [23:0] inputBuf_8_fu_170;
reg   [23:0] inputBuf_9_fu_174;
reg   [23:0] inputBuf_10_fu_178;
reg   [23:0] inputBuf_11_fu_182;
reg   [23:0] inputBuf_12_fu_186;
reg   [23:0] inputBuf_13_fu_190;
reg   [23:0] inputBuf_14_fu_194;
reg   [23:0] inputBuf_15_fu_198;
reg   [31:0] nf_fu_202;
wire   [31:0] nf_5_fu_659_p3;
reg   [31:0] ap_sig_allocacmp_nf_2;
wire   [23:0] tmp_fu_358_p33;
wire   [3:0] tmp_fu_358_p34;
wire   [31:0] nf_4_fu_647_p2;
wire   [0:0] icmp_ln302_fu_653_p2;
wire   [1:0] r_fu_682_p1;
wire   [1:0] r_4_fu_723_p4;
wire   [1:0] r_7_fu_760_p4;
wire   [1:0] r_10_fu_797_p4;
wire   [1:0] r_11_fu_814_p4;
wire   [1:0] mul_ln90_1_fu_849_p0;
wire  signed [3:0] mul_ln90_1_fu_849_p2;
wire   [1:0] mul_ln90_2_fu_865_p0;
wire  signed [3:0] mul_ln90_2_fu_865_p2;
wire   [1:0] mul_ln90_3_fu_881_p0;
wire  signed [3:0] mul_ln90_3_fu_881_p2;
wire   [1:0] mul_ln90_5_fu_897_p0;
wire  signed [3:0] mul_ln90_5_fu_897_p2;
wire   [1:0] mul_ln90_9_fu_913_p0;
wire  signed [3:0] mul_ln90_9_fu_913_p2;
wire  signed [4:0] grp_fu_1019_p3;
wire  signed [4:0] grp_fu_1001_p3;
wire  signed [4:0] grp_fu_1010_p3;
wire  signed [4:0] grp_fu_1036_p3;
wire  signed [5:0] sext_ln169_7_fu_932_p1;
wire  signed [5:0] sext_ln169_6_fu_929_p1;
wire  signed [8:0] sext_ln169_1_fu_951_p1;
wire   [8:0] select_ln272_fu_944_p3;
wire  signed [5:0] grp_fu_1054_p3;
wire  signed [8:0] sext_ln169_3_fu_960_p1;
wire   [8:0] add_ln169_1_fu_954_p2;
wire  signed [5:0] grp_fu_1045_p3;
wire  signed [6:0] sext_ln169_8_fu_972_p1;
wire  signed [6:0] sext_ln169_5_fu_969_p1;
wire   [6:0] add_ln169_10_fu_975_p2;
wire  signed [8:0] sext_ln169_9_fu_981_p1;
wire   [8:0] add_ln169_4_fu_963_p2;
wire   [1:0] grp_fu_1001_p0;
wire   [1:0] grp_fu_1010_p0;
wire   [1:0] grp_fu_1019_p0;
wire   [1:0] grp_fu_1028_p0;
wire   [1:0] grp_fu_1036_p0;
wire   [1:0] grp_fu_1045_p0;
wire   [1:0] grp_fu_1054_p0;
reg    grp_fu_1001_ce;
reg    grp_fu_1010_ce;
reg    grp_fu_1019_ce;
reg    grp_fu_1028_ce;
reg    grp_fu_1036_ce;
reg    grp_fu_1045_ce;
reg    grp_fu_1054_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
reg    ap_ST_iter4_fsm_state5_blk;
reg    ap_ST_iter5_fsm_state6_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] grp_fu_1001_p00;
wire   [3:0] grp_fu_1010_p00;
wire   [3:0] grp_fu_1019_p00;
wire   [3:0] grp_fu_1028_p00;
wire   [3:0] grp_fu_1036_p00;
wire   [3:0] grp_fu_1045_p00;
wire   [3:0] grp_fu_1054_p00;
wire   [3:0] mul_ln90_1_fu_849_p00;
wire   [3:0] mul_ln90_2_fu_865_p00;
wire   [3:0] mul_ln90_3_fu_881_p00;
wire   [3:0] mul_ln90_5_fu_897_p00;
wire   [3:0] mul_ln90_9_fu_913_p00;
reg    ap_condition_150;
wire   [3:0] tmp_fu_358_p1;
wire   [3:0] tmp_fu_358_p3;
wire   [3:0] tmp_fu_358_p5;
wire   [3:0] tmp_fu_358_p7;
wire   [3:0] tmp_fu_358_p9;
wire   [3:0] tmp_fu_358_p11;
wire   [3:0] tmp_fu_358_p13;
wire   [3:0] tmp_fu_358_p15;
wire  signed [3:0] tmp_fu_358_p17;
wire  signed [3:0] tmp_fu_358_p19;
wire  signed [3:0] tmp_fu_358_p21;
wire  signed [3:0] tmp_fu_358_p23;
wire  signed [3:0] tmp_fu_358_p25;
wire  signed [3:0] tmp_fu_358_p27;
wire  signed [3:0] tmp_fu_358_p29;
wire  signed [3:0] tmp_fu_358_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
#0 sf_fu_126 = 32'd0;
#0 i_fu_130 = 17'd0;
#0 empty_fu_134 = 9'd0;
#0 inputBuf_fu_138 = 24'd0;
#0 inputBuf_1_fu_142 = 24'd0;
#0 inputBuf_2_fu_146 = 24'd0;
#0 inputBuf_3_fu_150 = 24'd0;
#0 inputBuf_4_fu_154 = 24'd0;
#0 inputBuf_5_fu_158 = 24'd0;
#0 inputBuf_6_fu_162 = 24'd0;
#0 inputBuf_7_fu_166 = 24'd0;
#0 inputBuf_8_fu_170 = 24'd0;
#0 inputBuf_9_fu_174 = 24'd0;
#0 inputBuf_10_fu_178 = 24'd0;
#0 inputBuf_11_fu_182 = 24'd0;
#0 inputBuf_12_fu_186 = 24'd0;
#0 inputBuf_13_fu_190 = 24'd0;
#0 inputBuf_14_fu_194 = 24'd0;
#0 inputBuf_15_fu_198 = 24'd0;
#0 nf_fu_202 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) MVAU_hls_4_sparsemux_33_4_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 24 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 24 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 24 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 24 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 24 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 24 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 24 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 24 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 24 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 24 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 24 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 24 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 24 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 24 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 24 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 24 ),
    .def_WIDTH( 24 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 24 ))
sparsemux_33_4_24_1_1_U1(
    .din0(inputBuf_fu_138),
    .din1(inputBuf_1_fu_142),
    .din2(inputBuf_2_fu_146),
    .din3(inputBuf_3_fu_150),
    .din4(inputBuf_4_fu_154),
    .din5(inputBuf_5_fu_158),
    .din6(inputBuf_6_fu_162),
    .din7(inputBuf_7_fu_166),
    .din8(inputBuf_8_fu_170),
    .din9(inputBuf_9_fu_174),
    .din10(inputBuf_10_fu_178),
    .din11(inputBuf_11_fu_182),
    .din12(inputBuf_12_fu_186),
    .din13(inputBuf_13_fu_190),
    .din14(inputBuf_14_fu_194),
    .din15(inputBuf_15_fu_198),
    .def(tmp_fu_358_p33),
    .sel(tmp_fu_358_p34),
    .dout(tmp_fu_358_p35)
);

MVAU_hls_4_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U2(
    .din0(mul_ln90_1_fu_849_p0),
    .din1(local_temp_1_reg_1234_pp0_iter2_reg),
    .dout(mul_ln90_1_fu_849_p2)
);

MVAU_hls_4_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U3(
    .din0(mul_ln90_2_fu_865_p0),
    .din1(local_temp_2_reg_1239_pp0_iter2_reg),
    .dout(mul_ln90_2_fu_865_p2)
);

MVAU_hls_4_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U4(
    .din0(mul_ln90_3_fu_881_p0),
    .din1(local_temp_3_reg_1244_pp0_iter2_reg),
    .dout(mul_ln90_3_fu_881_p2)
);

MVAU_hls_4_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U5(
    .din0(mul_ln90_5_fu_897_p0),
    .din1(local_temp_5_reg_1254_pp0_iter2_reg),
    .dout(mul_ln90_5_fu_897_p2)
);

MVAU_hls_4_mul_2ns_2s_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .dout_WIDTH( 4 ))
mul_2ns_2s_4_1_1_U6(
    .din0(mul_ln90_9_fu_913_p0),
    .din1(local_temp_9_reg_1274_pp0_iter2_reg),
    .dout(mul_ln90_9_fu_913_p2)
);

MVAU_hls_4_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1001_p0),
    .din1(local_temp_reg_1229),
    .din2(mul_ln90_1_fu_849_p2),
    .ce(grp_fu_1001_ce),
    .dout(grp_fu_1001_p3)
);

MVAU_hls_4_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1010_p0),
    .din1(local_temp_4_reg_1249),
    .din2(mul_ln90_2_fu_865_p2),
    .ce(grp_fu_1010_ce),
    .dout(grp_fu_1010_p3)
);

MVAU_hls_4_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1019_p0),
    .din1(local_temp_7_reg_1264),
    .din2(mul_ln90_5_fu_897_p2),
    .ce(grp_fu_1019_ce),
    .dout(grp_fu_1019_p3)
);

MVAU_hls_4_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1028_p0),
    .din1(local_temp_10_reg_1279),
    .din2(mul_ln90_9_fu_913_p2),
    .ce(grp_fu_1028_ce),
    .dout(grp_fu_1028_p3)
);

MVAU_hls_4_mac_muladd_2ns_2s_4s_5_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 5 ))
mac_muladd_2ns_2s_4s_5_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1036_p0),
    .din1(local_temp_11_reg_1284),
    .din2(mul_ln90_3_fu_881_p2),
    .ce(grp_fu_1036_ce),
    .dout(grp_fu_1036_p3)
);

MVAU_hls_4_mac_muladd_2ns_2s_5s_6_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mac_muladd_2ns_2s_5s_6_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1045_p0),
    .din1(local_temp_6_reg_1259_pp0_iter1_reg),
    .din2(grp_fu_1001_p3),
    .ce(grp_fu_1045_ce),
    .dout(grp_fu_1045_p3)
);

MVAU_hls_4_mac_muladd_2ns_2s_5s_6_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 6 ))
mac_muladd_2ns_2s_5s_6_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1054_p0),
    .din1(local_temp_8_reg_1269_pp0_iter1_reg),
    .din2(grp_fu_1019_p3),
    .ce(grp_fu_1054_ce),
    .dout(grp_fu_1054_p3)
);

MVAU_hls_4_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b0) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if ((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_225 <= tmp_fu_358_p35;
    end else if (((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd14)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & 
    (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd0)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd1)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 
    == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd2)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd3)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 
    == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd4)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd5)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 
    == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd6)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd7)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) 
    & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd8)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd9)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) 
    | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd10)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd11)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) 
    & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd12)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd13)) | (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) 
    | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd15)))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_225 <= in0_V_TDATA;
    end else if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_inElem_reg_225 <= ap_phi_reg_pp0_iter0_inElem_reg_225;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_150)) begin
        if ((icmp_ln249_fu_288_p2 == 1'd0)) begin
            i_fu_130 <= i_2_fu_294_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_130 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_150)) begin
        if (((icmp_ln249_fu_288_p2 == 1'd0) & (icmp_ln290_fu_636_p2 == 1'd1))) begin
            nf_fu_202 <= nf_5_fu_659_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nf_fu_202 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_150)) begin
        if (((icmp_ln249_fu_288_p2 == 1'd0) & (icmp_ln290_fu_636_p2 == 1'd1))) begin
            sf_fu_126 <= 32'd0;
        end else if (((icmp_ln249_fu_288_p2 == 1'd0) & (icmp_ln290_fu_636_p2 == 1'd0))) begin
            sf_fu_126 <= sf_2_fu_630_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_126 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        add_ln169_9_reg_1438 <= add_ln169_9_fu_935_p2;
        add_ln169_reg_1423 <= grp_fu_1028_p3;
        icmp_ln249_reg_1187_pp0_iter4_reg <= icmp_ln249_reg_1187_pp0_iter3_reg;
        icmp_ln272_reg_1224_pp0_iter4_reg <= icmp_ln272_reg_1224_pp0_iter3_reg;
        icmp_ln290_reg_1289_pp0_iter4_reg <= icmp_ln290_reg_1289_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln249_reg_1187 <= icmp_ln249_fu_288_p2;
        icmp_ln272_reg_1224 <= icmp_ln272_fu_510_p2;
        icmp_ln290_reg_1289 <= icmp_ln290_fu_636_p2;
        local_temp_10_reg_1279 <= {{weights_V_TDATA[21:20]}};
        local_temp_11_reg_1284 <= {{weights_V_TDATA[23:22]}};
        local_temp_1_reg_1234 <= {{weights_V_TDATA[3:2]}};
        local_temp_2_reg_1239 <= {{weights_V_TDATA[5:4]}};
        local_temp_3_reg_1244 <= {{weights_V_TDATA[7:6]}};
        local_temp_4_reg_1249 <= {{weights_V_TDATA[9:8]}};
        local_temp_5_reg_1254 <= {{weights_V_TDATA[11:10]}};
        local_temp_6_reg_1259 <= {{weights_V_TDATA[13:12]}};
        local_temp_7_reg_1264 <= {{weights_V_TDATA[15:14]}};
        local_temp_8_reg_1269 <= {{weights_V_TDATA[17:16]}};
        local_temp_9_reg_1274 <= {{weights_V_TDATA[19:18]}};
        local_temp_reg_1229 <= local_temp_fu_516_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln249_reg_1187_pp0_iter1_reg <= icmp_ln249_reg_1187;
        icmp_ln272_reg_1224_pp0_iter1_reg <= icmp_ln272_reg_1224;
        icmp_ln290_reg_1289_pp0_iter1_reg <= icmp_ln290_reg_1289;
        local_temp_1_reg_1234_pp0_iter1_reg <= local_temp_1_reg_1234;
        local_temp_2_reg_1239_pp0_iter1_reg <= local_temp_2_reg_1239;
        local_temp_3_reg_1244_pp0_iter1_reg <= local_temp_3_reg_1244;
        local_temp_5_reg_1254_pp0_iter1_reg <= local_temp_5_reg_1254;
        local_temp_6_reg_1259_pp0_iter1_reg <= local_temp_6_reg_1259;
        local_temp_8_reg_1269_pp0_iter1_reg <= local_temp_8_reg_1269;
        local_temp_9_reg_1274_pp0_iter1_reg <= local_temp_9_reg_1274;
        r_1_reg_1303 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[3:2]}};
        r_2_reg_1308 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[5:4]}};
        r_3_reg_1313 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[7:6]}};
        r_5_reg_1328 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[11:10]}};
        r_6_reg_1333 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[13:12]}};
        r_8_reg_1348 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[17:16]}};
        r_9_reg_1353 <= {{ap_phi_reg_pp0_iter1_inElem_reg_225[19:18]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln249_reg_1187_pp0_iter2_reg <= icmp_ln249_reg_1187_pp0_iter1_reg;
        icmp_ln272_reg_1224_pp0_iter2_reg <= icmp_ln272_reg_1224_pp0_iter1_reg;
        icmp_ln290_reg_1289_pp0_iter2_reg <= icmp_ln290_reg_1289_pp0_iter1_reg;
        local_temp_1_reg_1234_pp0_iter2_reg <= local_temp_1_reg_1234_pp0_iter1_reg;
        local_temp_2_reg_1239_pp0_iter2_reg <= local_temp_2_reg_1239_pp0_iter1_reg;
        local_temp_3_reg_1244_pp0_iter2_reg <= local_temp_3_reg_1244_pp0_iter1_reg;
        local_temp_5_reg_1254_pp0_iter2_reg <= local_temp_5_reg_1254_pp0_iter1_reg;
        local_temp_9_reg_1274_pp0_iter2_reg <= local_temp_9_reg_1274_pp0_iter1_reg;
        r_1_reg_1303_pp0_iter2_reg <= r_1_reg_1303;
        r_2_reg_1308_pp0_iter2_reg <= r_2_reg_1308;
        r_3_reg_1313_pp0_iter2_reg <= r_3_reg_1313;
        r_5_reg_1328_pp0_iter2_reg <= r_5_reg_1328;
        r_9_reg_1353_pp0_iter2_reg <= r_9_reg_1353;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln249_reg_1187_pp0_iter3_reg <= icmp_ln249_reg_1187_pp0_iter2_reg;
        icmp_ln272_reg_1224_pp0_iter3_reg <= icmp_ln272_reg_1224_pp0_iter2_reg;
        icmp_ln290_reg_1289_pp0_iter3_reg <= icmp_ln290_reg_1289_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (icmp_ln249_reg_1187_pp0_iter4_reg == 1'd0) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        empty_fu_134 <= outElem_fu_985_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd10))) begin
        inputBuf_10_fu_178 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd11))) begin
        inputBuf_11_fu_182 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd12))) begin
        inputBuf_12_fu_186 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd13))) begin
        inputBuf_13_fu_190 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd14))) begin
        inputBuf_14_fu_194 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd15))) begin
        inputBuf_15_fu_198 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd1))) begin
        inputBuf_1_fu_142 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd2))) begin
        inputBuf_2_fu_146 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd3))) begin
        inputBuf_3_fu_150 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd4))) begin
        inputBuf_4_fu_154 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd5))) begin
        inputBuf_5_fu_158 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd6))) begin
        inputBuf_6_fu_162 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd7))) begin
        inputBuf_7_fu_166 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd8))) begin
        inputBuf_8_fu_170 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd9))) begin
        inputBuf_9_fu_174 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (icmp_ln253_fu_304_p2 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (trunc_ln249_fu_300_p1 == 4'd0))) begin
        inputBuf_fu_138 <= in0_V_TDATA;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_pp0_stage0_iter2)) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4_pp0_stage0_iter3)) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state5_pp0_stage0_iter4)) begin
        ap_ST_iter4_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_iter4_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5))) begin
        ap_ST_iter5_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_iter5_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter5_fsm_state0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 17'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_130;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_nf_2 = 32'd0;
    end else begin
        ap_sig_allocacmp_nf_2 = nf_fu_202;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_sf_1 = sf_fu_126;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) 
    & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_1001_ce = 1'b1;
    end else begin
        grp_fu_1001_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) 
    & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_1010_ce = 1'b1;
    end else begin
        grp_fu_1010_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) 
    & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_1019_ce = 1'b1;
    end else begin
        grp_fu_1019_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) 
    & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_1028_ce = 1'b1;
    end else begin
        grp_fu_1028_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) 
    & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_1036_ce = 1'b1;
    end else begin
        grp_fu_1036_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6)) | (~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
        grp_fu_1045_ce = 1'b1;
    end else begin
        grp_fu_1045_ce = 1'b0;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter5_fsm_state6)) | (~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter2_fsm_state3)))) begin
        grp_fu_1054_ce = 1'b1;
    end else begin
        grp_fu_1054_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op66_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (ap_predicate_op66_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op231_write_state6 == 1'b1) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (ap_predicate_op231_write_state6 == 1'b1) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln249_fu_288_p2 == 1'd0))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b0 == ap_block_state1_pp0_stage0_iter0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter2_fsm_state3) & (1'b0 == ap_block_state3_pp0_stage0_iter2))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & ((1'b0 == ap_CS_iter2_fsm_state3) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state3_pp0_stage0_iter2) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter3_fsm_state4) & (1'b0 == ap_block_state4_pp0_stage0_iter3))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & ((1'b0 == ap_CS_iter3_fsm_state4) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3))))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state4_pp0_stage0_iter3) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if ((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & ((1'b0 == ap_CS_iter4_fsm_state5) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4))))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else if (((~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (icmp_ln249_reg_1187_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_iter5_fsm_state6)) | (~((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)) & (1'b1 == ap_CS_iter4_fsm_state5) & (1'b0 == ap_block_state5_pp0_stage0_iter4)))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state5_pp0_stage0_iter4) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

assign add_ln169_10_fu_975_p2 = ($signed(sext_ln169_8_fu_972_p1) + $signed(sext_ln169_5_fu_969_p1));

assign add_ln169_1_fu_954_p2 = ($signed(sext_ln169_1_fu_951_p1) + $signed(select_ln272_fu_944_p3));

assign add_ln169_4_fu_963_p2 = ($signed(sext_ln169_3_fu_960_p1) + $signed(add_ln169_1_fu_954_p2));

assign add_ln169_9_fu_935_p2 = ($signed(sext_ln169_7_fu_932_p1) + $signed(sext_ln169_6_fu_929_p1));

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state0 = ap_CS_iter5_fsm[32'd0];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((weights_V_TVALID == 1'b0) & (icmp_ln249_fu_288_p2 == 1'd0)) | ((ap_predicate_op66_read_state1 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)));
end

always @ (*) begin
    ap_block_state6_io = ((ap_predicate_op231_write_state6 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((ap_predicate_op231_write_state6 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_150 = (~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((1'b1 == ap_CS_iter4_fsm_state5) & (1'b1 == ap_block_state5_pp0_stage0_iter4)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (1'b1 == ap_block_state6_pp0_stage0_iter5)))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_inElem_reg_225 = 'bx;

always @ (*) begin
    ap_predicate_op231_write_state6 = ((icmp_ln290_reg_1289_pp0_iter4_reg == 1'd1) & (icmp_ln249_reg_1187_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op66_read_state1 = ((icmp_ln253_fu_304_p2 == 1'd1) & (icmp_ln249_fu_288_p2 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign grp_fu_1001_p0 = grp_fu_1001_p00;

assign grp_fu_1001_p00 = r_fu_682_p1;

assign grp_fu_1010_p0 = grp_fu_1010_p00;

assign grp_fu_1010_p00 = r_4_fu_723_p4;

assign grp_fu_1019_p0 = grp_fu_1019_p00;

assign grp_fu_1019_p00 = r_7_fu_760_p4;

assign grp_fu_1028_p0 = grp_fu_1028_p00;

assign grp_fu_1028_p00 = r_10_fu_797_p4;

assign grp_fu_1036_p0 = grp_fu_1036_p00;

assign grp_fu_1036_p00 = r_11_fu_814_p4;

assign grp_fu_1045_p0 = grp_fu_1045_p00;

assign grp_fu_1045_p00 = r_6_reg_1333;

assign grp_fu_1054_p0 = grp_fu_1054_p00;

assign grp_fu_1054_p00 = r_8_reg_1348;

assign i_2_fu_294_p2 = (ap_sig_allocacmp_i_1 + 17'd1);

assign icmp_ln249_fu_288_p2 = ((ap_sig_allocacmp_i_1 == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln253_fu_304_p2 = ((ap_sig_allocacmp_nf_2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln272_fu_510_p2 = ((ap_sig_allocacmp_sf_1 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln290_fu_636_p2 = ((sf_2_fu_630_p2 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_653_p2 = ((nf_4_fu_647_p2 == 32'd64) ? 1'b1 : 1'b0);

assign local_temp_fu_516_p1 = weights_V_TDATA[1:0];

assign mul_ln90_1_fu_849_p0 = mul_ln90_1_fu_849_p00;

assign mul_ln90_1_fu_849_p00 = r_1_reg_1303_pp0_iter2_reg;

assign mul_ln90_2_fu_865_p0 = mul_ln90_2_fu_865_p00;

assign mul_ln90_2_fu_865_p00 = r_2_reg_1308_pp0_iter2_reg;

assign mul_ln90_3_fu_881_p0 = mul_ln90_3_fu_881_p00;

assign mul_ln90_3_fu_881_p00 = r_3_reg_1313_pp0_iter2_reg;

assign mul_ln90_5_fu_897_p0 = mul_ln90_5_fu_897_p00;

assign mul_ln90_5_fu_897_p00 = r_5_reg_1328_pp0_iter2_reg;

assign mul_ln90_9_fu_913_p0 = mul_ln90_9_fu_913_p00;

assign mul_ln90_9_fu_913_p00 = r_9_reg_1353_pp0_iter2_reg;

assign nf_4_fu_647_p2 = (ap_sig_allocacmp_nf_2 + 32'd1);

assign nf_5_fu_659_p3 = ((icmp_ln302_fu_653_p2[0:0] == 1'b1) ? 32'd0 : nf_4_fu_647_p2);

assign outElem_fu_985_p2 = ($signed(sext_ln169_9_fu_981_p1) + $signed(add_ln169_4_fu_963_p2));

assign out_V_TDATA = outElem_fu_985_p2;

assign r_10_fu_797_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[21:20]}};

assign r_11_fu_814_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[23:22]}};

assign r_4_fu_723_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[9:8]}};

assign r_7_fu_760_p4 = {{ap_phi_reg_pp0_iter1_inElem_reg_225[15:14]}};

assign r_fu_682_p1 = ap_phi_reg_pp0_iter1_inElem_reg_225[1:0];

assign select_ln272_fu_944_p3 = ((icmp_ln272_reg_1224_pp0_iter4_reg[0:0] == 1'b1) ? 9'd0 : empty_fu_134);

assign sext_ln169_1_fu_951_p1 = add_ln169_reg_1423;

assign sext_ln169_3_fu_960_p1 = grp_fu_1054_p3;

assign sext_ln169_5_fu_969_p1 = grp_fu_1045_p3;

assign sext_ln169_6_fu_929_p1 = grp_fu_1010_p3;

assign sext_ln169_7_fu_932_p1 = grp_fu_1036_p3;

assign sext_ln169_8_fu_972_p1 = $signed(add_ln169_9_reg_1438);

assign sext_ln169_9_fu_981_p1 = $signed(add_ln169_10_fu_975_p2);

assign sf_2_fu_630_p2 = (ap_sig_allocacmp_sf_1 + 32'd1);

assign tmp_fu_358_p33 = 'bx;

assign tmp_fu_358_p34 = ap_sig_allocacmp_sf_1[3:0];

assign trunc_ln249_fu_300_p1 = ap_sig_allocacmp_sf_1[3:0];

endmodule //MVAU_hls_4_Matrix_Vector_Activate_Stream_Batch
